/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Meet
 */
public class Delete_Information extends javax.swing.JFrame {

    /**
     * Creates new form Delete_Information
     */
    public Delete_Information() {
        initComponents();
        get_table_recover_button.setVisible(false);
        get_table_combobox.setVisible(false);
        get_table_done_button.setVisible(false);
        get_column_combobox.setVisible(false);
        get_column_textfield.setVisible(false);
        get_column_done_button1.setVisible(false);
        RECOVER_ins.setVisible(false);
        RECOVER_button_all1.setVisible(false);
        RECOVER_button_ins.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        get_table_combobox = new javax.swing.JComboBox<>();
        get_column_combobox = new javax.swing.JComboBox<>();
        get_column_textfield = new javax.swing.JTextField();
        RECOVER_ins = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        get_all_button = new javax.swing.JButton();
        get_column_done_button1 = new javax.swing.JButton();
        recover_button = new javax.swing.JButton();
        get_table_done_button = new javax.swing.JButton();
        get_all_button1 = new javax.swing.JButton();
        get_table_recover_button = new javax.swing.JButton();
        RECOVER_button_ins = new javax.swing.JButton();
        RECOVER_button_all1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        get_table_combobox.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        get_table_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USER1", "Patient", "Donor", "Doctor", "Organization", "Organ_Available", "Transaction", "Organization_Head" }));
        get_table_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_table_comboboxActionPerformed(evt);
            }
        });

        get_column_combobox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        get_column_combobox.setMaximumRowCount(1000);
        get_column_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_column_comboboxActionPerformed(evt);
            }
        });

        get_column_textfield.setBackground(new java.awt.Color(0, 102, 102));
        get_column_textfield.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        get_column_textfield.setForeground(new java.awt.Color(255, 255, 255));
        get_column_textfield.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        RECOVER_ins.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        RECOVER_ins.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\images\\Recover.jpg")); // NOI18N
        RECOVER_ins.setText("RECOVER");
        RECOVER_ins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RECOVER_insActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Delete Information Record");

        get_all_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        get_all_button.setText("GET ALL");
        get_all_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_all_buttonActionPerformed(evt);
            }
        });

        get_column_done_button1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        get_column_done_button1.setText("Done");
        get_column_done_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_column_done_button1ActionPerformed(evt);
            }
        });

        recover_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        recover_button.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\images\\Recover.jpg")); // NOI18N
        recover_button.setText("RECOVER");
        recover_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recover_buttonActionPerformed(evt);
            }
        });

        get_table_done_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        get_table_done_button.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\images\\Done (1).jpg")); // NOI18N
        get_table_done_button.setText("done");
        get_table_done_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_table_done_buttonActionPerformed(evt);
            }
        });

        get_all_button1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        get_all_button1.setText("GET TABLEWISE");
        get_all_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_all_button1ActionPerformed(evt);
            }
        });

        get_table_recover_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        get_table_recover_button.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\images\\Done (1).jpg")); // NOI18N
        get_table_recover_button.setText("Done");
        get_table_recover_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_table_recover_buttonActionPerformed(evt);
            }
        });

        RECOVER_button_ins.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        RECOVER_button_ins.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\images\\Recover.jpg")); // NOI18N
        RECOVER_button_ins.setText("RECOVER ALL");
        RECOVER_button_ins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RECOVER_button_insActionPerformed(evt);
            }
        });

        RECOVER_button_all1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        RECOVER_button_all1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\images\\Recover.jpg")); // NOI18N
        RECOVER_button_all1.setText("RECOVER ALL");
        RECOVER_button_all1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RECOVER_button_all1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168)
                .addComponent(RECOVER_ins)
                .addGap(225, 225, 225))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton5)
                        .addGap(604, 604, 604)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(get_all_button1)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(get_all_button)
                                .addGap(284, 284, 284)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(recover_button)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(get_column_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)
                                        .addComponent(get_column_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(get_table_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(get_table_recover_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(get_table_done_button))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(815, 815, 815)
                        .addComponent(RECOVER_button_ins)
                        .addGap(64, 64, 64)
                        .addComponent(RECOVER_button_all1)))
                .addContainerGap(174, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(1690, Short.MAX_VALUE)
                    .addComponent(get_column_done_button1)
                    .addGap(164, 164, 164)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jLabel1))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recover_button)
                    .addComponent(get_all_button)
                    .addComponent(get_all_button1))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(get_column_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(get_column_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(get_table_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(get_table_done_button)
                    .addComponent(get_table_recover_button))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(RECOVER_ins, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RECOVER_button_ins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RECOVER_button_all1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(282, 282, 282)
                    .addComponent(get_column_done_button1)
                    .addContainerGap(679, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void get_table_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_table_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_get_table_comboboxActionPerformed

    private void get_column_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_column_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_get_column_comboboxActionPerformed

    private void get_column_done_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_column_done_button1ActionPerformed
        RECOVER_ins.setVisible(false);

        RECOVER_button_all1.setVisible(false);
        RECOVER_button_ins.setVisible(false);
        DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
//                   tm.setRowCount(0);
                                  tm.setRowCount(0);
 
        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
//            System.out.println(jComboBox1.getSelectedItem());
//            System.out.println(jTextField1.getText());
              String table=get_table_combobox.getSelectedItem().toString();
                String colname=get_column_combobox.getSelectedItem().toString();
                String value=get_column_textfield.getText();
ResultSet rs = st.executeQuery("select * from recovery_table where tablename = '"+table+"' order by QUERY_TIME DESC");
ResultSetMetaData meta=rs.getMetaData();
int numberOfColumns=meta.getColumnCount();
            while(rs.next()){
//                int no = rs.getInt(1);
//                String name = rs.getString(2);
//                System.out.println("no: "+no+" name: "+name);
String temp=rs.getString(3);
String a[]=temp.split(",");
                System.out.println();
                System.out.println("selected"+get_column_combobox.getSelectedIndex());
if(a[get_column_combobox.getSelectedIndex()].equals(value)){
                
            
                    Object[] rowData=new Object[numberOfColumns];
                    for (int i = 0; i < rowData.length; ++i) {
                    rowData[i]=rs.getObject(i+1);
                }
                  tm.addRow(rowData);
                  RECOVER_ins.setVisible(true);

            }
            }
        }catch(Exception e){
            e.printStackTrace();
        }

//        RECOVER_ins.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_get_column_done_button1ActionPerformed

    private void get_all_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_all_buttonActionPerformed
RECOVER_ins.setVisible(false);
        RECOVER_button_all1.setVisible(false);
        RECOVER_button_ins.setVisible(false);
    DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
//                   tm.setRowCount(0);
                                  tm.setRowCount(0);
 
        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
//            System.out.println(jComboBox1.getSelectedItem());
//            System.out.println(jTextField1.getText());
//            System.out.println(value);
ResultSet rs = st.executeQuery("select * from recovery_table order by QUERY_TIME DESC");
ResultSetMetaData meta=rs.getMetaData();
int numberOfColumns=meta.getColumnCount();
            while(rs.next()){
//                int no = rs.getInt(1);
//                String name = rs.getString(2);
//                System.out.println("no: "+no+" name: "+name);
                    Object[] rowData=new Object[numberOfColumns];
                    for (int i = 0; i < rowData.length; ++i) {
                    rowData[i]=rs.getObject(i+1);
                }
                    
        RECOVER_button_all1.setVisible(true);
                  tm.addRow(rowData);
            }
          
        }catch(Exception e){
            e.printStackTrace();
        }
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_get_all_buttonActionPerformed

    private void recover_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recover_buttonActionPerformed
        get_table_done_button.setVisible(false);
        get_column_combobox.setVisible(false);
        get_column_textfield.setVisible(false);
        get_column_done_button1.setVisible(false);
        RECOVER_ins.setVisible(false);

        
        
        get_table_combobox.setVisible(true);
 get_table_recover_button.setVisible(true);
                
        

// TODO add your handling code here:
    }//GEN-LAST:event_recover_buttonActionPerformed

    private void get_table_done_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_table_done_buttonActionPerformed
RECOVER_button_ins.setVisible(false);
        DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
//                   tm.setRowCount(0);
                                  tm.setRowCount(0);
 
        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
//            System.out.println(jComboBox1.getSelectedItem());
//            System.out.println(jTextField1.getText());
//            System.out.println(value);
String value=get_table_combobox.getSelectedItem().toString();
        
ResultSet rs = st.executeQuery("select * from recovery_table where tablename='"+value+"' order by QUERY_TIME DESC");
ResultSetMetaData meta=rs.getMetaData();
int numberOfColumns=meta.getColumnCount();
            while(rs.next()){
//                int no = rs.getInt(1);
//                String name = rs.getString(2);
//                System.out.println("no: "+no+" name: "+name);
                    Object[] rowData=new Object[numberOfColumns];
                    for (int i = 0; i < rowData.length; ++i) {
                    rowData[i]=rs.getObject(i+1);
                }
                  tm.addRow(rowData);
RECOVER_button_ins.setVisible(true);
            }
          
        }catch(Exception e){
            e.printStackTrace();
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_get_table_done_buttonActionPerformed

    private void get_all_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_all_button1ActionPerformed
RECOVER_ins.setVisible(false);
        RECOVER_button_all1.setVisible(false);
        RECOVER_button_ins.setVisible(false);
    
        get_table_recover_button.setVisible(false);
        get_column_combobox.setVisible(false);
        get_column_textfield.setVisible(false);
        get_column_done_button1.setVisible(false);
        
        

 get_table_combobox.setVisible(true);
        get_table_done_button.setVisible(true);
       // TODO add your handling code here:
    }//GEN-LAST:event_get_all_button1ActionPerformed

    private void get_table_recover_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_table_recover_buttonActionPerformed
 get_column_combobox.setVisible(false);
        get_column_textfield.setVisible(false);
        get_column_done_button1.setVisible(false);
        
        DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
//                   tm.setRowCount(0);
                                  tm.setRowCount(0);
 
        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
//            System.out.println(jComboBox1.getSelectedItem());
//            System.out.println(jTextField1.getText());
//            System.out.println(value);
String value=get_table_combobox.getSelectedItem().toString();
        
ResultSet rs = st.executeQuery("select * from recovery_table where tablename='"+value+"' order by QUERY_TIME DESC");
ResultSetMetaData meta=rs.getMetaData();
int numberOfColumns=meta.getColumnCount();
            while(rs.next()){
//                int no = rs.getInt(1);
//                String name = rs.getString(2);
//                System.out.println("no: "+no+" name: "+name);
                    Object[] rowData=new Object[numberOfColumns];
                    for (int i = 0; i < rowData.length; ++i) {
                    rowData[i]=rs.getObject(i+1);
                }
                  tm.addRow(rowData);
                  get_column_combobox.setVisible(true);
        get_column_textfield.setVisible(true);
        get_column_done_button1.setVisible(true);
        
            }
          
        }catch(Exception e){
            e.printStackTrace();
        }
        
       
        get_table_done_button.setVisible(false);
//        RECOVER_button.setVisible(false);
        
        RECOVER_ins.setVisible(false);
        RECOVER_button_all1.setVisible(false);
        RECOVER_button_ins.setVisible(false);
    
        
        String table=get_table_combobox.getSelectedItem().toString();
        
        if(table.equals("USER1")){
            get_column_combobox.removeAllItems();
            get_column_combobox.addItem("USER_ID");
            get_column_combobox.addItem("NAME");
            get_column_combobox.addItem("DATE_OF_BIRTH");
            get_column_combobox.addItem("MEDICAL_INSURANCE");
            get_column_combobox.addItem("MEDICAL_HISTORY");
            get_column_combobox.addItem("STREET");
            get_column_combobox.addItem("CITY");
            get_column_combobox.addItem("STATE");
        }
        else if(table.equals("Patient")){
            get_column_combobox.removeAllItems();
            get_column_combobox.addItem("Patient_ID"); 
            get_column_combobox.addItem("organ_req");
get_column_combobox.addItem("reason_of_procurement");
get_column_combobox.addItem("Doctor_ID");
get_column_combobox.addItem("User_ID");
            /*
            



            */
        }
        else if(table.equals("Donor")){
            get_column_combobox.removeAllItems();
            
            get_column_combobox.addItem("Donor_ID");
get_column_combobox.addItem("organ_donated");
get_column_combobox.addItem("reason_of_donation");
get_column_combobox.addItem("Organization_ID");
get_column_combobox.addItem("User_ID");

        }
        else if(table.equals("Doctor")){
            get_column_combobox.removeAllItems();
get_column_combobox.addItem("Doctor_ID");
            get_column_combobox.addItem("Doctor_Name");
get_column_combobox.addItem("Department_Name");
get_column_combobox.addItem("organization_ID");
        }
        else if(table.equals("Organization")){
            get_column_combobox.removeAllItems();
            get_column_combobox.addItem("Organization_ID");
get_column_combobox.addItem("Organization_name");
get_column_combobox.addItem("Location");
get_column_combobox.addItem("Government_approved");

        }
        else if(table.equals("Organ_Available")){
            get_column_combobox.removeAllItems();
            get_column_combobox.addItem("Organ_ID");
 get_column_combobox.addItem("Organ_name");
 get_column_combobox.addItem("Donor_ID");
 
        }
        else if(table.equals("Transaction")){
            get_column_combobox.removeAllItems();
 get_column_combobox.addItem("Patient_ID");
            get_column_combobox.addItem("Organ_ID");
            get_column_combobox.addItem("Donor_ID");
            get_column_combobox.addItem("Date_of_transaction");
            get_column_combobox.addItem("Status");
            
        }
        else if(table.equals("Organization_Head")){
            get_column_combobox.removeAllItems();
            get_column_combobox.addItem("Organization_ID");
            get_column_combobox.addItem("Employee_ID");
            get_column_combobox.addItem("Name");
            get_column_combobox.addItem("Date_of_joining");
            get_column_combobox.addItem("Term_length");
        }
         // TODO add your handling code here:
    }//GEN-LAST:event_get_table_recover_buttonActionPerformed

    private void RECOVER_insActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RECOVER_insActionPerformed
DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
//                   tm.setRowCount(0);
                                  tm.setRowCount(0);
 
        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
//            System.out.println(jComboBox1.getSelectedItem());
//            System.out.println(jTextField1.getText());
              String table=get_table_combobox.getSelectedItem().toString();
                String colname=get_column_combobox.getSelectedItem().toString();
                String value=get_column_textfield.getText();
ResultSet rs = st.executeQuery("select * from recovery_table where tablename = '"+table+"' order by QUERY_TIME DESC");
ResultSetMetaData meta=rs.getMetaData();
int numberOfColumns=meta.getColumnCount();

            while(rs.next()){
//                int no = rs.getInt(1);
//                String name = rs.getString(2);
//                System.out.println("no: "+no+" name: "+name);
String temp=rs.getString(3);
String a[]=temp.split(",");
                System.out.println();
//                System.out.println("selected"+get_column_combobox.getSelectedIndex());
if(a[get_column_combobox.getSelectedIndex()].equals(value)){
                StringBuffer s=new StringBuffer();
            for (int i = 0; i < a.length; i++) {
        s.append("'").append(a[i]).append("'");
        if(a.length-1!=i){
            s.append(",");
        }
    }
            System.out.println(s.toString());
            String data=rs.getString(3);
            String tablename=rs.getString(2);
            st.execute("insert into "+rs.getString(2)+" values("+s.toString()+") ");
            st.execute("delete from recovery_table where tablename = '"+tablename+"' and data= '"+data+"'");
                    }
            }
            JOptionPane.showMessageDialog(rootPane, "VALUES RECYCLED SUCCESSFULLY!","DONE",JOptionPane.PLAIN_MESSAGE);
 
        }catch(Exception e){
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_RECOVER_insActionPerformed

    private void RECOVER_button_all1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RECOVER_button_all1ActionPerformed
DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
//                   tm.setRowCount(0);
                                  tm.setRowCount(0);
 
        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
            Statement st2 = conn.createStatement();
//            System.out.println(jComboBox1.getSelectedItem());
//            System.out.println(jTextField1.getText());
              String table=get_table_combobox.getSelectedItem().toString();
//                String colname=get_column_combobox.getSelectedItem().toString();
//                String value=get_column_textfield.getText();
ResultSet rs = st.executeQuery("select * from recovery_table");
ResultSetMetaData meta=rs.getMetaData();
int numberOfColumns=meta.getColumnCount();
            while(rs.next()){
//                int no = rs.getInt(1);
//                String name = rs.getString(2);
//                System.out.println("no: "+no+" name: "+name);
String temp=rs.getString(3);
String a[]=temp.split(",");
                System.out.println();
//                System.out.println("selected"+get_column_combobox.getSelectedIndex());
              StringBuffer s=new StringBuffer();
            for (int i = 0; i < a.length; i++) {
        s.append("'").append(a[i]).append("'");
        if(a.length-1!=i){
            s.append(",");
    }
                   }
            
            System.out.println(s.toString());
             
            String data=rs.getString(3);
            String tablename=rs.getString(2);
                System.out.println(tablename);
            st2.execute("insert into "+tablename+" values("+s.toString()+") ");
                System.out.println("1");
            }
            
             st2.execute("delete from recovery_table ");

        }catch(Exception e){
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(rootPane, "VALUES RECYCLED SUCCESSFULLY!","DONE",JOptionPane.PLAIN_MESSAGE);
 
        // TODO add your handling code here:
    }//GEN-LAST:event_RECOVER_button_all1ActionPerformed

    private void RECOVER_button_insActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RECOVER_button_insActionPerformed
DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
//                   tm.setRowCount(0);
                                  tm.setRowCount(0);
 
        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
            Statement st2 = conn.createStatement();
//            System.out.println(jComboBox1.getSelectedItem());
//            System.out.println(jTextField1.getText());
              String table=get_table_combobox.getSelectedItem().toString();
//                String colname=get_column_combobox.getSelectedItem().toString();
//                String value=get_column_textfield.getText();
ResultSet rs = st.executeQuery("select * from recovery_table where tablename= '"+table+"' ");
ResultSetMetaData meta=rs.getMetaData();
int numberOfColumns=meta.getColumnCount();
            while(rs.next()){
//                int no = rs.getInt(1);
//                String name = rs.getString(2);
//                System.out.println("no: "+no+" name: "+name);
String temp=rs.getString(3);
String a[]=temp.split(",");
                System.out.println();
//                System.out.println("selected"+get_column_combobox.getSelectedIndex());
              StringBuffer s=new StringBuffer();
            for (int i = 0; i < a.length; i++) {
        s.append("'").append(a[i]).append("'");
        if(a.length-1!=i){
            s.append(",");
    }
                   }
            
            System.out.println(s.toString());
             
            String data=rs.getString(3);
            String tablename=rs.getString(2);
                System.out.println(tablename);
            st2.execute("insert into "+tablename+" values("+s.toString()+") ");
                System.out.println("1");
            }
            
             st2.execute("delete from recovery_table where tablename='"+table+"'");

        }catch(Exception e){
            e.printStackTrace();
        }        
JOptionPane.showMessageDialog(rootPane, "VALUES RECYCLED SUCCESSFULLY!","DONE",JOptionPane.PLAIN_MESSAGE);
 // TODO add your handling code here:
    }//GEN-LAST:event_RECOVER_button_insActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       try {
            //                jTextField4.setText("Welcome");
            //  System.out.println(user);
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Delete_Screen_2.class.getName()).log(Level.SEVERE, null, ex);
        }
                 this.dispose();
                 
              // new projectjava.LoginPage.c1();
               new dbms.SIUD().setVisible(true);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete_Information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RECOVER_button_all1;
    private javax.swing.JButton RECOVER_button_ins;
    private javax.swing.JButton RECOVER_ins;
    private javax.swing.JButton get_all_button;
    private javax.swing.JButton get_all_button1;
    private javax.swing.JComboBox<String> get_column_combobox;
    private javax.swing.JButton get_column_done_button1;
    private javax.swing.JTextField get_column_textfield;
    private javax.swing.JComboBox<String> get_table_combobox;
    private javax.swing.JButton get_table_done_button;
    private javax.swing.JButton get_table_recover_button;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton recover_button;
    // End of variables declaration//GEN-END:variables
}
