/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Meet
 */
public class Delete_Screen extends javax.swing.JFrame {

    /**
     * Creates new form Delete_Screen
     */
    public Delete_Screen() {
        initComponents();
        delete_by_user_combobox.setVisible(false);
        delete_by_patient_combobox.setVisible(false);
        delete_by_donor_combobox.setVisible(false);
        delete_by_doctor_combobox.setVisible(false);
        
        delete_by_user_done_button.setVisible(false);
        delete_by_patient_done_button.setVisible(false);
        delete_by_donor_done_button.setVisible(false);
        delete_by_doctor_done_button.setVisible(false);
        
        delete_by_user_textfield.setVisible(false);
        delete_by_patient_textfield.setVisible(false);
        delete_by_donor_textfield.setVisible(false);
        delete_by_doctor_textfield.setVisible(false);
        
        DISPLAY_USERS_BUTTON.setVisible(false);
        DISPLAY_PATIENTS_BUTTON.setVisible(false);
        DISPLAY_DONOR_BUTTON.setVisible(false);
        DISPLAY_DOCTOR_BUTTON.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        delete_by_patient_button = new javax.swing.JButton();
        delete_by_user_button = new javax.swing.JButton();
        delete_by_doctor_button = new javax.swing.JButton();
        delete_by_donor_button = new javax.swing.JButton();
        delete_by_user_combobox = new javax.swing.JComboBox<>();
        delete_by_patient_combobox = new javax.swing.JComboBox<>();
        delete_by_donor_combobox = new javax.swing.JComboBox<>();
        delete_by_doctor_combobox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        delete_by_donor_textfield = new javax.swing.JTextField();
        delete_by_patient_textfield = new javax.swing.JTextField();
        delete_by_user_textfield = new javax.swing.JTextField();
        delete_by_doctor_textfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        delete_by_patient_done_button = new javax.swing.JButton();
        delete_by_doctor_done_button = new javax.swing.JButton();
        delete_by_donor_done_button = new javax.swing.JButton();
        delete_by_user_done_button = new javax.swing.JButton();
        DISPLAY_USERS_BUTTON = new javax.swing.JButton();
        DISPLAY_PATIENTS_BUTTON = new javax.swing.JButton();
        DISPLAY_DONOR_BUTTON = new javax.swing.JButton();
        DISPLAY_DOCTOR_BUTTON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setText("Back");

        delete_by_patient_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        delete_by_patient_button.setText("Delete By Patient ");
        delete_by_patient_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_by_patient_buttonActionPerformed(evt);
            }
        });

        delete_by_user_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        delete_by_user_button.setText("Delete By User ");
        delete_by_user_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_by_user_buttonActionPerformed(evt);
            }
        });

        delete_by_doctor_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        delete_by_doctor_button.setText("Delete By Doctor ");
        delete_by_doctor_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_by_doctor_buttonActionPerformed(evt);
            }
        });

        delete_by_donor_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        delete_by_donor_button.setText("Delete By Donor ");
        delete_by_donor_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_by_donor_buttonActionPerformed(evt);
            }
        });

        delete_by_user_combobox.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        delete_by_user_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USER_ID", "NAME", "DATE_OF_BIRTH", "MEDICAL_INSURANCE", "MEDICAL_HISTORY", "STREET", "CITY", "STATE" }));
        delete_by_user_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_by_user_comboboxActionPerformed(evt);
            }
        });

        delete_by_patient_combobox.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        delete_by_patient_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PATIENT_ID", "ORGAN_REQ", "REASON_OF_PROCUREMENT", "DOCTOR_ID", "USER_ID" }));

        delete_by_donor_combobox.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        delete_by_donor_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DONOR_ID", "ORGAN_DONATED", "REASON_OF_DONATION", "ORGANIZATION_ID", "USER_ID" }));

        delete_by_doctor_combobox.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        delete_by_doctor_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DOCTOR_ID", "DOCTOR_NAME", "DEPARTMENT_NAME", "ORGANIZATION_ID" }));

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        delete_by_donor_textfield.setBackground(new java.awt.Color(0, 102, 102));
        delete_by_donor_textfield.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        delete_by_donor_textfield.setForeground(new java.awt.Color(255, 255, 255));
        delete_by_donor_textfield.setBorder(null);

        delete_by_patient_textfield.setBackground(new java.awt.Color(0, 102, 102));
        delete_by_patient_textfield.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        delete_by_patient_textfield.setForeground(new java.awt.Color(255, 255, 255));
        delete_by_patient_textfield.setBorder(null);

        delete_by_user_textfield.setBackground(new java.awt.Color(0, 102, 102));
        delete_by_user_textfield.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        delete_by_user_textfield.setForeground(new java.awt.Color(255, 255, 255));
        delete_by_user_textfield.setBorder(null);

        delete_by_doctor_textfield.setBackground(new java.awt.Color(0, 102, 102));
        delete_by_doctor_textfield.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        delete_by_doctor_textfield.setForeground(new java.awt.Color(255, 255, 255));
        delete_by_doctor_textfield.setBorder(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        delete_by_patient_done_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        delete_by_patient_done_button.setText("Done");
        delete_by_patient_done_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_by_patient_done_buttonActionPerformed(evt);
            }
        });

        delete_by_doctor_done_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        delete_by_doctor_done_button.setText("Done");
        delete_by_doctor_done_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_by_doctor_done_buttonActionPerformed(evt);
            }
        });

        delete_by_donor_done_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        delete_by_donor_done_button.setText("Done");
        delete_by_donor_done_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_by_donor_done_buttonActionPerformed(evt);
            }
        });

        delete_by_user_done_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        delete_by_user_done_button.setText("Done");
        delete_by_user_done_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_by_user_done_buttonActionPerformed(evt);
            }
        });

        DISPLAY_USERS_BUTTON.setText("DISPLAY USERS");
        DISPLAY_USERS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DISPLAY_USERS_BUTTONActionPerformed(evt);
            }
        });

        DISPLAY_PATIENTS_BUTTON.setText("DISPLAY PATIENT");
        DISPLAY_PATIENTS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DISPLAY_PATIENTS_BUTTONActionPerformed(evt);
            }
        });

        DISPLAY_DONOR_BUTTON.setText("DISPLAY DONOR");
        DISPLAY_DONOR_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DISPLAY_DONOR_BUTTONActionPerformed(evt);
            }
        });

        DISPLAY_DOCTOR_BUTTON.setText("DISPLAY DOCTOR");
        DISPLAY_DOCTOR_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DISPLAY_DOCTOR_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(delete_by_donor_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(delete_by_patient_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(delete_by_doctor_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(delete_by_user_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(138, 138, 138)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(delete_by_doctor_done_button)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(delete_by_donor_combobox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(delete_by_user_combobox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(delete_by_patient_combobox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(delete_by_user_done_button)
                                            .addComponent(delete_by_patient_done_button)
                                            .addComponent(delete_by_donor_done_button)
                                            .addComponent(delete_by_doctor_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(117, 117, 117)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(delete_by_patient_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(delete_by_donor_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(delete_by_doctor_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(delete_by_user_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(517, 517, 517)
                .addComponent(DISPLAY_USERS_BUTTON)
                .addGap(149, 149, 149)
                .addComponent(DISPLAY_PATIENTS_BUTTON)
                .addGap(139, 139, 139)
                .addComponent(DISPLAY_DONOR_BUTTON)
                .addGap(170, 170, 170)
                .addComponent(DISPLAY_DOCTOR_BUTTON)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jButton5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delete_by_user_button)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(delete_by_user_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(delete_by_user_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)
                        .addComponent(delete_by_user_done_button)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delete_by_patient_button)
                            .addComponent(delete_by_patient_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete_by_patient_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(11, 11, 11)
                        .addComponent(delete_by_patient_done_button)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delete_by_donor_button)
                            .addComponent(delete_by_donor_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete_by_donor_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(delete_by_donor_done_button)
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(delete_by_doctor_button)
                                    .addComponent(delete_by_doctor_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(delete_by_doctor_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(delete_by_doctor_done_button)
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DISPLAY_USERS_BUTTON)
                            .addComponent(DISPLAY_PATIENTS_BUTTON)
                            .addComponent(DISPLAY_DONOR_BUTTON)
                            .addComponent(DISPLAY_DOCTOR_BUTTON))
                        .addGap(69, 69, 69))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delete_by_user_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_by_user_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_by_user_comboboxActionPerformed

    private void delete_by_user_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_by_user_buttonActionPerformed
        delete_by_patient_combobox.setVisible(false);
        delete_by_donor_combobox.setVisible(false);
        delete_by_doctor_combobox.setVisible(false);
        
        delete_by_patient_done_button.setVisible(false);
        delete_by_donor_done_button.setVisible(false);
        delete_by_doctor_done_button.setVisible(false);
        
        delete_by_patient_textfield.setVisible(false);
        delete_by_donor_textfield.setVisible(false);
        delete_by_doctor_textfield.setVisible(false);
        
        DISPLAY_PATIENTS_BUTTON.setVisible(false);
        DISPLAY_DONOR_BUTTON.setVisible(false);
        DISPLAY_DOCTOR_BUTTON.setVisible(false);

        delete_by_user_combobox.setVisible(true);
        delete_by_user_done_button.setVisible(true);
        delete_by_user_textfield.setVisible(true);
        DISPLAY_USERS_BUTTON.setVisible(true);
                
        
// TODO add your handling code here:
    }//GEN-LAST:event_delete_by_user_buttonActionPerformed

    private void delete_by_patient_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_by_patient_buttonActionPerformed
 
        delete_by_user_combobox.setVisible(false);
        delete_by_donor_combobox.setVisible(false);
        delete_by_doctor_combobox.setVisible(false);
        
        delete_by_user_done_button.setVisible(false);
        delete_by_donor_done_button.setVisible(false);
        delete_by_doctor_done_button.setVisible(false);
        
        delete_by_user_textfield.setVisible(false);
        delete_by_donor_textfield.setVisible(false);
        delete_by_doctor_textfield.setVisible(false);
        
        DISPLAY_USERS_BUTTON.setVisible(false);
        DISPLAY_DONOR_BUTTON.setVisible(false);
        DISPLAY_DOCTOR_BUTTON.setVisible(false);        // TODO add your handling code here:
        
        
        delete_by_patient_combobox.setVisible(true);
        delete_by_patient_done_button.setVisible(true);
        delete_by_patient_textfield.setVisible(true);
        DISPLAY_PATIENTS_BUTTON.setVisible(true);
        
        
        
    }//GEN-LAST:event_delete_by_patient_buttonActionPerformed

    private void delete_by_donor_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_by_donor_buttonActionPerformed

        delete_by_user_combobox.setVisible(false);
        delete_by_patient_combobox.setVisible(false);
        delete_by_doctor_combobox.setVisible(false);
        
        delete_by_user_done_button.setVisible(false);
        delete_by_patient_done_button.setVisible(false);
        delete_by_doctor_done_button.setVisible(false);
        
        delete_by_user_textfield.setVisible(false);
        delete_by_patient_textfield.setVisible(false);
        delete_by_doctor_textfield.setVisible(false);
        
        DISPLAY_USERS_BUTTON.setVisible(false);
        DISPLAY_PATIENTS_BUTTON.setVisible(false);
        DISPLAY_DOCTOR_BUTTON.setVisible(false);        // TODO add your handling code here:
        
        delete_by_donor_combobox.setVisible(true);
        delete_by_donor_done_button.setVisible(true);
        delete_by_donor_textfield.setVisible(true);
        DISPLAY_DONOR_BUTTON.setVisible(true);
        
    }//GEN-LAST:event_delete_by_donor_buttonActionPerformed

    private void delete_by_doctor_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_by_doctor_buttonActionPerformed

        delete_by_user_combobox.setVisible(false);
        delete_by_patient_combobox.setVisible(false);
        delete_by_donor_combobox.setVisible(false);
        
        delete_by_user_done_button.setVisible(false);
        delete_by_patient_done_button.setVisible(false);
        delete_by_donor_done_button.setVisible(false);
        
        delete_by_user_textfield.setVisible(false);
        delete_by_patient_textfield.setVisible(false);
        delete_by_donor_textfield.setVisible(false);
        
        DISPLAY_USERS_BUTTON.setVisible(false);
        DISPLAY_PATIENTS_BUTTON.setVisible(false);
        DISPLAY_DONOR_BUTTON.setVisible(false);
            // TODO add your handling code here:
            
            
        delete_by_doctor_combobox.setVisible(true);
        delete_by_doctor_done_button.setVisible(true);
        delete_by_doctor_textfield.setVisible(true);
        DISPLAY_DOCTOR_BUTTON.setVisible(true);
        
    }//GEN-LAST:event_delete_by_doctor_buttonActionPerformed

    private void delete_by_user_done_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_by_user_done_buttonActionPerformed
DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
//                   tm.setRowCount(0);
                                  tm.setRowCount(0);
 
        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
//            System.out.println(jComboBox1.getSelectedItem());
//            System.out.println(jTextField1.getText());
                String colname=delete_by_user_combobox.getSelectedItem().toString();
                String value=delete_by_user_textfield.getText();
ResultSet rs = st.executeQuery("delete from user1 where "+colname+" = '"+value+"'");
//ResultSetMetaData meta=rs.getMetaData();
//int numberOfColumns=meta.getColumnCount();
//            while(rs.next()){
////                int no = rs.getInt(1);
////                String name = rs.getString(2);
////                System.out.println("no: "+no+" name: "+name);
//                    Object[] rowData=new Object[numberOfColumns];
//                    for (int i = 0; i < rowData.length; ++i) {
//                    rowData[i]=rs.getObject(i+1);
//                }
//                  tm.addRow(rowData);
//            }
            System.out.println("DONE");
        }catch(Exception e){
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_by_user_done_buttonActionPerformed

    private void delete_by_patient_done_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_by_patient_done_buttonActionPerformed
DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
//                   tm.setRowCount(0);
                                  tm.setRowCount(0);
 
        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
//            System.out.println(jComboBox1.getSelectedItem());
//            System.out.println(jTextField1.getText());
                String colname=delete_by_patient_combobox.getSelectedItem().toString();
                String value=delete_by_patient_textfield.getText();
ResultSet rs = st.executeQuery("delete from patient where "+colname+" = '"+value+"'");
//ResultSetMetaData meta=rs.getMetaData();
//int numberOfColumns=meta.getColumnCount();
//            while(rs.next()){
////                int no = rs.getInt(1);
////                String name = rs.getString(2);
////                System.out.println("no: "+no+" name: "+name);
//                    Object[] rowData=new Object[numberOfColumns];
//                    for (int i = 0; i < rowData.length; ++i) {
//                    rowData[i]=rs.getObject(i+1);
//                }
//                  tm.addRow(rowData);
//            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_by_patient_done_buttonActionPerformed

    private void delete_by_donor_done_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_by_donor_done_buttonActionPerformed
DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
//                   tm.setRowCount(0);
                                  tm.setRowCount(0);
 
        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
//            System.out.println(jComboBox1.getSelectedItem());
//            System.out.println(jTextField1.getText());
                String colname=delete_by_donor_combobox.getSelectedItem().toString();
                String value=delete_by_donor_textfield.getText();
ResultSet rs = st.executeQuery("delete from donor where "+colname+" = '"+value+"'");
//ResultSetMetaData meta=rs.getMetaData();
//int numberOfColumns=meta.getColumnCount();
//            while(rs.next()){
////                int no = rs.getInt(1);
////                String name = rs.getString(2);
////                System.out.println("no: "+no+" name: "+name);
//                    Object[] rowData=new Object[numberOfColumns];
//                    for (int i = 0; i < rowData.length; ++i) {
//                    rowData[i]=rs.getObject(i+1);
//                }
//                  tm.addRow(rowData);
//            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_by_donor_done_buttonActionPerformed

    private void delete_by_doctor_done_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_by_doctor_done_buttonActionPerformed
DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
//                   tm.setRowCount(0);
                                  tm.setRowCount(0);
 
        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
//            System.out.println(jComboBox1.getSelectedItem());
//            System.out.println(jTextField1.getText());
                String colname=delete_by_doctor_combobox.getSelectedItem().toString();
                String value=delete_by_doctor_textfield.getText();
ResultSet rs = st.executeQuery("delete from doctor where "+colname+" = '"+value+"'");
//ResultSetMetaData meta=rs.getMetaData();
//int numberOfColumns=meta.getColumnCount();
//            while(rs.next()){
////                int no = rs.getInt(1);
////                String name = rs.getString(2);
////                System.out.println("no: "+no+" name: "+name);
//                    Object[] rowData=new Object[numberOfColumns];
//                    for (int i = 0; i < rowData.length; ++i) {
//                    rowData[i]=rs.getObject(i+1);
//                }
//                  tm.addRow(rowData);
//            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_delete_by_doctor_done_buttonActionPerformed

    private void DISPLAY_USERS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DISPLAY_USERS_BUTTONActionPerformed
DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
//                   tm.setRowCount(0);
                                  tm.setRowCount(0);
 
        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
ResultSet rs = st.executeQuery("select USER_ID,NAME,DATE_OF_BIRTH,MEDICAL_INSURANCE,MEDICAL_HISTORY,STREET,CITY,STATE from user1");
ResultSetMetaData meta=rs.getMetaData();
int numberOfColumns=meta.getColumnCount();
            while(rs.next()){
                    Object[] rowData=new Object[numberOfColumns];
                    for (int i = 0; i < rowData.length; ++i) {
                    rowData[i]=rs.getObject(i+1);
                }
                  tm.addRow(rowData);
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_DISPLAY_USERS_BUTTONActionPerformed

    private void DISPLAY_PATIENTS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DISPLAY_PATIENTS_BUTTONActionPerformed
DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
//                   tm.setRowCount(0);
                                  tm.setRowCount(0);
 
        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
//            System.out.println(jComboBox1.getSelectedItem());
//            System.out.println(jTextField1.getText());
//                String colname=serach_by_user_ComboBox.getSelectedItem().toString();
//                String value=serach_by_user_textfield.getText();
ResultSet rs = st.executeQuery("select PATIENT_ID,ORGAN_REQ,REASON_OF_PROCUREMENT,DOCTOR_ID,USER_ID from patient ");
ResultSetMetaData meta=rs.getMetaData();
int numberOfColumns=meta.getColumnCount();
            while(rs.next()){
//                int no = rs.getInt(1);
//                String name = rs.getString(2);
//                System.out.println("no: "+no+" name: "+name);
                    Object[] rowData=new Object[numberOfColumns];
                    for (int i = 0; i < rowData.length; ++i) {
                    rowData[i]=rs.getObject(i+1);
                }
                  tm.addRow(rowData);
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_DISPLAY_PATIENTS_BUTTONActionPerformed

    private void DISPLAY_DONOR_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DISPLAY_DONOR_BUTTONActionPerformed
DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
//                   tm.setRowCount(0);
                                  tm.setRowCount(0);
 
        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
//            System.out.println(jComboBox1.getSelectedItem());
//            System.out.println(jTextField1.getText());
//                String colname=serach_by_user_ComboBox.getSelectedItem().toString();
//                String value=serach_by_user_textfield.getText();
ResultSet rs = st.executeQuery("select DONOR_ID,ORGAN_DONATED,REASON_OF_DONATION,ORGANIZATION_ID,USER_ID from donor ");
ResultSetMetaData meta=rs.getMetaData();
int numberOfColumns=meta.getColumnCount();
            while(rs.next()){
//                int no = rs.getInt(1);
//                String name = rs.getString(2);
//                System.out.println("no: "+no+" name: "+name);
                    Object[] rowData=new Object[numberOfColumns];
                    for (int i = 0; i < rowData.length; ++i) {
                    rowData[i]=rs.getObject(i+1);
                }
                  tm.addRow(rowData);
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_DISPLAY_DONOR_BUTTONActionPerformed

    private void DISPLAY_DOCTOR_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DISPLAY_DOCTOR_BUTTONActionPerformed
DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
//                   tm.setRowCount(0);
                                  tm.setRowCount(0);
 
        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
//            System.out.println(jComboBox1.getSelectedItem());
//            System.out.println(jTextField1.getText());
//                String colname=serach_by_user_ComboBox.getSelectedItem().toString();
//                String value=serach_by_user_textfield.getText();
ResultSet rs = st.executeQuery("select DOCTOR_ID,DOCTOR_NAME,DEPARTMENT_NAME,ORGANIZATION_ID from doctor ");
ResultSetMetaData meta=rs.getMetaData();
int numberOfColumns=meta.getColumnCount();
            while(rs.next()){
//                int no = rs.getInt(1);
//                String name = rs.getString(2);
//                System.out.println("no: "+no+" name: "+name);
                    Object[] rowData=new Object[numberOfColumns];
                    for (int i = 0; i < rowData.length; ++i) {
                    rowData[i]=rs.getObject(i+1);
                }
                  tm.addRow(rowData);
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_DISPLAY_DOCTOR_BUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DISPLAY_DOCTOR_BUTTON;
    private javax.swing.JButton DISPLAY_DONOR_BUTTON;
    private javax.swing.JButton DISPLAY_PATIENTS_BUTTON;
    private javax.swing.JButton DISPLAY_USERS_BUTTON;
    private javax.swing.JButton delete_by_doctor_button;
    private javax.swing.JComboBox<String> delete_by_doctor_combobox;
    private javax.swing.JButton delete_by_doctor_done_button;
    private javax.swing.JTextField delete_by_doctor_textfield;
    private javax.swing.JButton delete_by_donor_button;
    private javax.swing.JComboBox<String> delete_by_donor_combobox;
    private javax.swing.JButton delete_by_donor_done_button;
    private javax.swing.JTextField delete_by_donor_textfield;
    private javax.swing.JButton delete_by_patient_button;
    private javax.swing.JComboBox<String> delete_by_patient_combobox;
    private javax.swing.JButton delete_by_patient_done_button;
    private javax.swing.JTextField delete_by_patient_textfield;
    private javax.swing.JButton delete_by_user_button;
    private javax.swing.JComboBox<String> delete_by_user_combobox;
    private javax.swing.JButton delete_by_user_done_button;
    private javax.swing.JTextField delete_by_user_textfield;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
