/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VARSHIL
 */
public class Insert_Screen_2 extends javax.swing.JFrame {

    /**
     * Creates new form Insert_Screen_2
     */
    public Insert_Screen_2() {
        initComponents();
        insert_organization_org_id_label.setVisible(false);
        insert_organization_name_label.setVisible(false);
        insert_organization_location_label.setVisible(false);
        insert_organization_govtapproved_label.setVisible(false);
        insert_organization_org_id_textfield.setVisible(false);
        insert_organization_name_textfield.setVisible(false);
        insert_organization_location_textfield.setVisible(false);
        insert_organization_govtapproved_textfield.setVisible(false);
        insert_organization_done_button.setVisible(false);
        
        
        insert_transaction_patient_id_label.setVisible(false);
        insert_transaction_organ_id_label.setVisible(false);
        insert_transaction_donor_id_label.setVisible(false);
        insert_transaction_date_of_transaction_label.setVisible(false);
        insert_transaction_status_label.setVisible(false);
        insert_transaction_patient_id_textfield.setVisible(false);
        insert_transaction_organ_id_textfield.setVisible(false);
        insert_transaction_donor_id_textfield.setVisible(false);
        insert_transaction_date_of_transaction_textfield.setVisible(false);
        insert_transaction_status_textfield.setVisible(false);
        insert_transaction_done_button.setVisible(false);
        
        
        insert_organavailable_org_id_label.setVisible(false);
        insert_organavailable_org_name_label.setVisible(false);
        insert_organavailable_donor_id_label.setVisible(false);
        insert_organavailable_org_id_textfield.setVisible(false);
        insert_organavailable_org_name_textfield.setVisible(false);
        insert_organavailable_donor_id_textfield.setVisible(false);
        insert_orgavailable_done_button.setVisible(false);
        
        
        
        insert_orghead_org_id_label.setVisible(false);
        insert_orghead_employee_id_label.setVisible(false);
        insert_orghead_name_label.setVisible(false);
        insert_orghead_date_of_joining_label.setVisible(false);
        insert_orghead_term_label.setVisible(false);
        insert_orghead_org_id_textfield.setVisible(false);
        insert_orghead_employee_id_textfield.setVisible(false);
        insert_orghead_name_textfield.setVisible(false);
        insert_orghead_date_of_joining_textfield.setVisible(false);
        insert_orghead_term_textfield.setVisible(false);
        insert_orghead_done_button.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        insert_organization_org_id_label = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        insert_organization_name_label = new javax.swing.JLabel();
        insert_organization_location_label = new javax.swing.JLabel();
        insert_organization_govtapproved_label = new javax.swing.JLabel();
        insert_organization_name_textfield = new javax.swing.JTextField();
        insert_organization_location_textfield = new javax.swing.JTextField();
        insert_organization_govtapproved_textfield = new javax.swing.JTextField();
        insert_organization_done_button = new javax.swing.JButton();
        insert_organavailable_org_id_label = new javax.swing.JLabel();
        insert_organavailable_org_name_label = new javax.swing.JLabel();
        insert_organavailable_donor_id_label = new javax.swing.JLabel();
        insert_organavailable_org_id_textfield = new javax.swing.JTextField();
        insert_organavailable_org_name_textfield = new javax.swing.JTextField();
        insert_organavailable_donor_id_textfield = new javax.swing.JTextField();
        insert_orgavailable_done_button = new javax.swing.JButton();
        insert_transaction_patient_id_label = new javax.swing.JLabel();
        insert_transaction_organ_id_label = new javax.swing.JLabel();
        insert_transaction_donor_id_label = new javax.swing.JLabel();
        insert_transaction_date_of_transaction_label = new javax.swing.JLabel();
        insert_transaction_status_label = new javax.swing.JLabel();
        insert_transaction_patient_id_textfield = new javax.swing.JTextField();
        insert_transaction_organ_id_textfield = new javax.swing.JTextField();
        insert_transaction_donor_id_textfield = new javax.swing.JTextField();
        insert_transaction_date_of_transaction_textfield = new javax.swing.JTextField();
        insert_transaction_status_textfield = new javax.swing.JTextField();
        insert_transaction_done_button = new javax.swing.JButton();
        insert_orghead_org_id_label = new javax.swing.JLabel();
        insert_orghead_employee_id_label = new javax.swing.JLabel();
        insert_orghead_name_label = new javax.swing.JLabel();
        insert_orghead_date_of_joining_label = new javax.swing.JLabel();
        insert_orghead_term_label = new javax.swing.JLabel();
        insert_orghead_org_id_textfield = new javax.swing.JTextField();
        insert_orghead_employee_id_textfield = new javax.swing.JTextField();
        insert_orghead_name_textfield = new javax.swing.JTextField();
        insert_orghead_date_of_joining_textfield = new javax.swing.JTextField();
        insert_orghead_term_textfield = new javax.swing.JTextField();
        insert_orghead_done_button = new javax.swing.JButton();
        DISPLAY_ORGANIZATION_BUTTON = new javax.swing.JButton();
        DISPLAY_TRANSACTIONS_BUTTON = new javax.swing.JButton();
        DISPLAY_ORGHEAD_BUTTON = new javax.swing.JButton();
        DISPLAY_ORGAN_BUTTON = new javax.swing.JButton();
        insert_organization_org_id_textfield = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\images\\Small_Insert.jpg")); // NOI18N
        jButton4.setText("Insert By Organization");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\images\\Small_Insert.jpg")); // NOI18N
        jButton5.setText("Insert By Organ Available");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        insert_organization_org_id_label.setBackground(new java.awt.Color(0, 102, 102));
        insert_organization_org_id_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_organization_org_id_label.setForeground(new java.awt.Color(255, 255, 255));
        insert_organization_org_id_label.setText("Organization ID");

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\images\\Back.jpg")); // NOI18N
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\images\\Small_Insert.jpg")); // NOI18N
        jButton7.setText("Insert By Transaction");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\images\\Small_Insert.jpg")); // NOI18N
        jButton8.setText("Insert By Organization Head");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        insert_organization_name_label.setBackground(new java.awt.Color(0, 102, 102));
        insert_organization_name_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_organization_name_label.setForeground(new java.awt.Color(255, 255, 255));
        insert_organization_name_label.setText("Organization Name");

        insert_organization_location_label.setBackground(new java.awt.Color(0, 102, 102));
        insert_organization_location_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_organization_location_label.setForeground(new java.awt.Color(255, 255, 255));
        insert_organization_location_label.setText("Location");

        insert_organization_govtapproved_label.setBackground(new java.awt.Color(0, 102, 102));
        insert_organization_govtapproved_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_organization_govtapproved_label.setForeground(new java.awt.Color(255, 255, 255));
        insert_organization_govtapproved_label.setText("Goverment Approved");

        insert_organization_name_textfield.setBackground(new java.awt.Color(0, 102, 102));
        insert_organization_name_textfield.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_organization_name_textfield.setForeground(new java.awt.Color(255, 255, 255));

        insert_organization_location_textfield.setBackground(new java.awt.Color(0, 102, 102));
        insert_organization_location_textfield.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_organization_location_textfield.setForeground(new java.awt.Color(255, 255, 255));

        insert_organization_govtapproved_textfield.setBackground(new java.awt.Color(0, 102, 102));
        insert_organization_govtapproved_textfield.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_organization_govtapproved_textfield.setForeground(new java.awt.Color(255, 255, 255));

        insert_organization_done_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        insert_organization_done_button.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\images\\Done (1).jpg")); // NOI18N
        insert_organization_done_button.setText("Done");
        insert_organization_done_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_organization_done_buttonActionPerformed(evt);
            }
        });

        insert_organavailable_org_id_label.setBackground(new java.awt.Color(0, 102, 102));
        insert_organavailable_org_id_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_organavailable_org_id_label.setForeground(new java.awt.Color(255, 255, 255));
        insert_organavailable_org_id_label.setText("Organization ID");

        insert_organavailable_org_name_label.setBackground(new java.awt.Color(0, 102, 102));
        insert_organavailable_org_name_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_organavailable_org_name_label.setForeground(new java.awt.Color(255, 255, 255));
        insert_organavailable_org_name_label.setText("Organization Name");

        insert_organavailable_donor_id_label.setBackground(new java.awt.Color(0, 102, 102));
        insert_organavailable_donor_id_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_organavailable_donor_id_label.setForeground(new java.awt.Color(255, 255, 255));
        insert_organavailable_donor_id_label.setText("Donor ID");

        insert_organavailable_org_id_textfield.setBackground(new java.awt.Color(0, 102, 102));
        insert_organavailable_org_id_textfield.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_organavailable_org_id_textfield.setForeground(new java.awt.Color(255, 255, 255));

        insert_organavailable_org_name_textfield.setBackground(new java.awt.Color(0, 102, 102));
        insert_organavailable_org_name_textfield.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_organavailable_org_name_textfield.setForeground(new java.awt.Color(255, 255, 255));

        insert_organavailable_donor_id_textfield.setBackground(new java.awt.Color(0, 102, 102));
        insert_organavailable_donor_id_textfield.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_organavailable_donor_id_textfield.setForeground(new java.awt.Color(255, 255, 255));

        insert_orgavailable_done_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        insert_orgavailable_done_button.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\images\\Done (1).jpg")); // NOI18N
        insert_orgavailable_done_button.setText("Done");
        insert_orgavailable_done_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_orgavailable_done_buttonActionPerformed(evt);
            }
        });

        insert_transaction_patient_id_label.setBackground(new java.awt.Color(0, 102, 102));
        insert_transaction_patient_id_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_transaction_patient_id_label.setForeground(new java.awt.Color(255, 255, 255));
        insert_transaction_patient_id_label.setText("Patient ID");

        insert_transaction_organ_id_label.setBackground(new java.awt.Color(0, 102, 102));
        insert_transaction_organ_id_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_transaction_organ_id_label.setForeground(new java.awt.Color(255, 255, 255));
        insert_transaction_organ_id_label.setText("Organ ID");

        insert_transaction_donor_id_label.setBackground(new java.awt.Color(0, 102, 102));
        insert_transaction_donor_id_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_transaction_donor_id_label.setForeground(new java.awt.Color(255, 255, 255));
        insert_transaction_donor_id_label.setText("Donor ID");

        insert_transaction_date_of_transaction_label.setBackground(new java.awt.Color(0, 102, 102));
        insert_transaction_date_of_transaction_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_transaction_date_of_transaction_label.setForeground(new java.awt.Color(255, 255, 255));
        insert_transaction_date_of_transaction_label.setText("Date Of Transaction");

        insert_transaction_status_label.setBackground(new java.awt.Color(0, 102, 102));
        insert_transaction_status_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_transaction_status_label.setForeground(new java.awt.Color(255, 255, 255));
        insert_transaction_status_label.setText("Status");

        insert_transaction_patient_id_textfield.setBackground(new java.awt.Color(0, 102, 102));
        insert_transaction_patient_id_textfield.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_transaction_patient_id_textfield.setForeground(new java.awt.Color(255, 255, 255));

        insert_transaction_organ_id_textfield.setBackground(new java.awt.Color(0, 102, 102));
        insert_transaction_organ_id_textfield.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_transaction_organ_id_textfield.setForeground(new java.awt.Color(255, 255, 255));

        insert_transaction_donor_id_textfield.setBackground(new java.awt.Color(0, 102, 102));
        insert_transaction_donor_id_textfield.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_transaction_donor_id_textfield.setForeground(new java.awt.Color(255, 255, 255));

        insert_transaction_date_of_transaction_textfield.setBackground(new java.awt.Color(0, 102, 102));
        insert_transaction_date_of_transaction_textfield.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_transaction_date_of_transaction_textfield.setForeground(new java.awt.Color(255, 255, 255));

        insert_transaction_status_textfield.setBackground(new java.awt.Color(0, 102, 102));
        insert_transaction_status_textfield.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_transaction_status_textfield.setForeground(new java.awt.Color(255, 255, 255));

        insert_transaction_done_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        insert_transaction_done_button.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\images\\Done (1).jpg")); // NOI18N
        insert_transaction_done_button.setText("Done");
        insert_transaction_done_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_transaction_done_buttonActionPerformed(evt);
            }
        });

        insert_orghead_org_id_label.setBackground(new java.awt.Color(0, 102, 102));
        insert_orghead_org_id_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_orghead_org_id_label.setForeground(new java.awt.Color(255, 255, 255));
        insert_orghead_org_id_label.setText("Organization ID");

        insert_orghead_employee_id_label.setBackground(new java.awt.Color(0, 102, 102));
        insert_orghead_employee_id_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_orghead_employee_id_label.setForeground(new java.awt.Color(255, 255, 255));
        insert_orghead_employee_id_label.setText("Employee ID");

        insert_orghead_name_label.setBackground(new java.awt.Color(0, 102, 102));
        insert_orghead_name_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_orghead_name_label.setForeground(new java.awt.Color(255, 255, 255));
        insert_orghead_name_label.setText("Name");

        insert_orghead_date_of_joining_label.setBackground(new java.awt.Color(0, 102, 102));
        insert_orghead_date_of_joining_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_orghead_date_of_joining_label.setForeground(new java.awt.Color(255, 255, 255));
        insert_orghead_date_of_joining_label.setText("Date Of Joining");

        insert_orghead_term_label.setBackground(new java.awt.Color(0, 102, 102));
        insert_orghead_term_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_orghead_term_label.setForeground(new java.awt.Color(255, 255, 255));
        insert_orghead_term_label.setText("Term Length");

        insert_orghead_org_id_textfield.setBackground(new java.awt.Color(0, 102, 102));
        insert_orghead_org_id_textfield.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_orghead_org_id_textfield.setForeground(new java.awt.Color(255, 255, 255));

        insert_orghead_employee_id_textfield.setBackground(new java.awt.Color(0, 102, 102));
        insert_orghead_employee_id_textfield.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_orghead_employee_id_textfield.setForeground(new java.awt.Color(255, 255, 255));

        insert_orghead_name_textfield.setBackground(new java.awt.Color(0, 102, 102));
        insert_orghead_name_textfield.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_orghead_name_textfield.setForeground(new java.awt.Color(255, 255, 255));

        insert_orghead_date_of_joining_textfield.setBackground(new java.awt.Color(0, 102, 102));
        insert_orghead_date_of_joining_textfield.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_orghead_date_of_joining_textfield.setForeground(new java.awt.Color(255, 255, 255));

        insert_orghead_term_textfield.setBackground(new java.awt.Color(0, 102, 102));
        insert_orghead_term_textfield.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_orghead_term_textfield.setForeground(new java.awt.Color(255, 255, 255));

        insert_orghead_done_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        insert_orghead_done_button.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\images\\Done (1).jpg")); // NOI18N
        insert_orghead_done_button.setText("Done");
        insert_orghead_done_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_orghead_done_buttonActionPerformed(evt);
            }
        });

        DISPLAY_ORGANIZATION_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DISPLAY_ORGANIZATION_BUTTON.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\images\\View.jpg")); // NOI18N
        DISPLAY_ORGANIZATION_BUTTON.setText("DISPLAY ORGANIZATION");
        DISPLAY_ORGANIZATION_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DISPLAY_ORGANIZATION_BUTTONActionPerformed(evt);
            }
        });

        DISPLAY_TRANSACTIONS_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DISPLAY_TRANSACTIONS_BUTTON.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\images\\View.jpg")); // NOI18N
        DISPLAY_TRANSACTIONS_BUTTON.setText("DISPLAY TRANSACTIONS");
        DISPLAY_TRANSACTIONS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DISPLAY_TRANSACTIONS_BUTTONActionPerformed(evt);
            }
        });

        DISPLAY_ORGHEAD_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DISPLAY_ORGHEAD_BUTTON.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\images\\View.jpg")); // NOI18N
        DISPLAY_ORGHEAD_BUTTON.setText("DISPLAY ORGANIZATION HEAD");
        DISPLAY_ORGHEAD_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DISPLAY_ORGHEAD_BUTTONActionPerformed(evt);
            }
        });

        DISPLAY_ORGAN_BUTTON.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        DISPLAY_ORGAN_BUTTON.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\images\\View.jpg")); // NOI18N
        DISPLAY_ORGAN_BUTTON.setText("DISPLAY ORGAN AVAILABLE");
        DISPLAY_ORGAN_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DISPLAY_ORGAN_BUTTONActionPerformed(evt);
            }
        });

        insert_organization_org_id_textfield.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        insert_organization_org_id_textfield.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(insert_organization_org_id_label)
                                            .addComponent(insert_organization_name_label)
                                            .addComponent(insert_organization_location_label)
                                            .addComponent(insert_organization_govtapproved_label))
                                        .addGap(80, 80, 80)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(insert_organization_location_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(insert_organization_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(insert_organization_govtapproved_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(insert_organization_org_id_textfield))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(insert_organavailable_org_id_label)
                                                    .addComponent(insert_organavailable_org_name_label)
                                                    .addComponent(insert_organavailable_donor_id_label))
                                                .addGap(69, 69, 69)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(insert_organavailable_donor_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(insert_organavailable_org_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(insert_organavailable_org_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(211, 211, 211))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(insert_orgavailable_done_button)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(insert_orghead_org_id_label)
                                                .addComponent(jButton8)
                                                .addComponent(insert_orghead_employee_id_label)
                                                .addComponent(insert_orghead_name_label)
                                                .addComponent(insert_orghead_date_of_joining_label)
                                                .addComponent(insert_orghead_term_label)))
                                        .addGap(151, 151, 151))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(insert_transaction_patient_id_label)
                                        .addGap(159, 159, 159)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(insert_transaction_organ_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(insert_transaction_patient_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(insert_transaction_donor_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(insert_transaction_date_of_transaction_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(insert_transaction_status_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(insert_transaction_date_of_transaction_label)
                                    .addComponent(insert_transaction_donor_id_label)
                                    .addComponent(insert_transaction_organ_id_label)
                                    .addComponent(insert_transaction_status_label))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(insert_transaction_done_button)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(insert_orghead_term_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(insert_orghead_date_of_joining_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(insert_orghead_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(insert_orghead_employee_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(insert_orghead_org_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(36, 36, 36)
                                        .addComponent(insert_orghead_done_button)
                                        .addGap(9, 9, 9))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(insert_organization_done_button)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DISPLAY_ORGANIZATION_BUTTON)
                                    .addComponent(DISPLAY_ORGAN_BUTTON))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DISPLAY_TRANSACTIONS_BUTTON)
                                    .addComponent(DISPLAY_ORGHEAD_BUTTON))
                                .addGap(206, 206, 206))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insert_organization_org_id_label)
                            .addComponent(insert_organavailable_org_id_label)
                            .addComponent(insert_organavailable_org_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insert_organization_org_id_textfield))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(insert_organization_name_label)
                                    .addComponent(insert_organization_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(insert_organization_location_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(insert_organization_location_label)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(insert_organavailable_org_name_label)
                                    .addComponent(insert_organavailable_org_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(insert_organavailable_donor_id_label)
                                    .addComponent(insert_organavailable_donor_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(insert_organization_govtapproved_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(insert_organization_govtapproved_label))
                                .addGap(22, 22, 22)
                                .addComponent(insert_organization_done_button))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(insert_orgavailable_done_button)))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton8))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insert_transaction_patient_id_label)
                            .addComponent(insert_transaction_patient_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insert_orghead_org_id_label)
                            .addComponent(insert_orghead_org_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insert_transaction_organ_id_label)
                    .addComponent(insert_transaction_organ_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insert_orghead_employee_id_label)
                    .addComponent(insert_orghead_employee_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insert_transaction_donor_id_label)
                            .addComponent(insert_transaction_donor_id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insert_orghead_name_label)
                            .addComponent(insert_orghead_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insert_transaction_date_of_transaction_label)
                            .addComponent(insert_transaction_date_of_transaction_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insert_orghead_date_of_joining_label)
                            .addComponent(insert_orghead_date_of_joining_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DISPLAY_ORGANIZATION_BUTTON)
                            .addComponent(DISPLAY_TRANSACTIONS_BUTTON))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DISPLAY_ORGAN_BUTTON)
                            .addComponent(DISPLAY_ORGHEAD_BUTTON))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insert_transaction_status_label)
                            .addComponent(insert_transaction_status_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insert_orghead_term_label)
                            .addComponent(insert_orghead_term_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insert_transaction_done_button)
                            .addComponent(insert_orghead_done_button))
                        .addGap(67, 67, 67))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        insert_organization_org_id_label.setVisible(true);
        insert_organization_name_label.setVisible(true);
        insert_organization_location_label.setVisible(true);
        insert_organization_govtapproved_label.setVisible(true);
        insert_organization_org_id_textfield.setVisible(true);
        insert_organization_name_textfield.setVisible(true);
        insert_organization_location_textfield.setVisible(true);
        insert_organization_govtapproved_textfield.setVisible(true);
        insert_organization_done_button.setVisible(true);
        
        
        insert_transaction_patient_id_label.setVisible(false);
        insert_transaction_organ_id_label.setVisible(false);
        insert_transaction_donor_id_label.setVisible(false);
        insert_transaction_date_of_transaction_label.setVisible(false);
        insert_transaction_status_label.setVisible(false);
        insert_transaction_patient_id_textfield.setVisible(false);
        insert_transaction_organ_id_textfield.setVisible(false);
        insert_transaction_donor_id_textfield.setVisible(false);
        insert_transaction_date_of_transaction_textfield.setVisible(false);
        insert_transaction_status_textfield.setVisible(false);
        insert_transaction_done_button.setVisible(false);
        
        
        insert_organavailable_org_id_label.setVisible(false);
        insert_organavailable_org_name_label.setVisible(false);
        insert_organavailable_donor_id_label.setVisible(false);
        insert_organavailable_org_id_textfield.setVisible(false);
        insert_organavailable_org_name_textfield.setVisible(false);
        insert_organavailable_donor_id_textfield.setVisible(false);
        insert_orgavailable_done_button.setVisible(false);
        
        
        
        insert_orghead_org_id_label.setVisible(false);
        insert_orghead_employee_id_label.setVisible(false);
        insert_orghead_name_label.setVisible(false);
        insert_orghead_date_of_joining_label.setVisible(false);
        insert_orghead_term_label.setVisible(false);
        insert_orghead_org_id_textfield.setVisible(false);
        insert_orghead_employee_id_textfield.setVisible(false);
        insert_orghead_name_textfield.setVisible(false);
        insert_orghead_date_of_joining_textfield.setVisible(false);
        insert_orghead_term_textfield.setVisible(false);
        insert_orghead_done_button.setVisible(false);
                // TODO add your handling code here:
                
                
                   Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        
        try{
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("Select count(*) from organization");
            while(rs.next()){
                int no = rs.getInt(1);
                insert_organization_org_id_textfield.setText(String.valueOf(no+1));
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
    

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
insert_organization_org_id_label.setVisible(false);
        insert_organization_name_label.setVisible(false);
        insert_organization_location_label.setVisible(false);
        insert_organization_govtapproved_label.setVisible(false);
        insert_organization_org_id_textfield.setVisible(false);
        insert_organization_name_textfield.setVisible(false);
        insert_organization_location_textfield.setVisible(false);
        insert_organization_govtapproved_textfield.setVisible(false);
        insert_organization_done_button.setVisible(false);
        
        
        insert_transaction_patient_id_label.setVisible(false);
        insert_transaction_organ_id_label.setVisible(false);
        insert_transaction_donor_id_label.setVisible(false);
        insert_transaction_date_of_transaction_label.setVisible(false);
        insert_transaction_status_label.setVisible(false);
        insert_transaction_patient_id_textfield.setVisible(false);
        insert_transaction_organ_id_textfield.setVisible(false);
        insert_transaction_donor_id_textfield.setVisible(false);
        insert_transaction_date_of_transaction_textfield.setVisible(false);
        insert_transaction_status_textfield.setVisible(false);
        insert_transaction_done_button.setVisible(false);
        
        
        insert_organavailable_org_id_label.setVisible(true);
        insert_organavailable_org_name_label.setVisible(true);
        insert_organavailable_donor_id_label.setVisible(true);
        insert_organavailable_org_id_textfield.setVisible(true);
        insert_organavailable_org_name_textfield.setVisible(true);
        insert_organavailable_donor_id_textfield.setVisible(true);
        insert_orgavailable_done_button.setVisible(true);
        
        
        
        insert_orghead_org_id_label.setVisible(false);
        insert_orghead_employee_id_label.setVisible(false);
        insert_orghead_name_label.setVisible(false);
        insert_orghead_date_of_joining_label.setVisible(false);
        insert_orghead_term_label.setVisible(false);
        insert_orghead_org_id_textfield.setVisible(false);
        insert_orghead_employee_id_textfield.setVisible(false);
        insert_orghead_name_textfield.setVisible(false);
        insert_orghead_date_of_joining_textfield.setVisible(false);
        insert_orghead_term_textfield.setVisible(false);
        insert_orghead_done_button.setVisible(false);
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
insert_organization_org_id_label.setVisible(false);
        insert_organization_name_label.setVisible(false);
        insert_organization_location_label.setVisible(false);
        insert_organization_govtapproved_label.setVisible(false);
        insert_organization_org_id_textfield.setVisible(false);
        insert_organization_name_textfield.setVisible(false);
        insert_organization_location_textfield.setVisible(false);
        insert_organization_govtapproved_textfield.setVisible(false);
        insert_organization_done_button.setVisible(false);
        
        
        insert_transaction_patient_id_label.setVisible(true);
        insert_transaction_organ_id_label.setVisible(true);
        insert_transaction_donor_id_label.setVisible(true);
        insert_transaction_date_of_transaction_label.setVisible(true);
        insert_transaction_status_label.setVisible(true);
        insert_transaction_patient_id_textfield.setVisible(true);
        insert_transaction_organ_id_textfield.setVisible(true);
        insert_transaction_donor_id_textfield.setVisible(true);
        insert_transaction_date_of_transaction_textfield.setVisible(true);
        insert_transaction_status_textfield.setVisible(true);
        insert_transaction_done_button.setVisible(true);
        
        
        insert_organavailable_org_id_label.setVisible(false);
        insert_organavailable_org_name_label.setVisible(false);
        insert_organavailable_donor_id_label.setVisible(false);
        insert_organavailable_org_id_textfield.setVisible(false);
        insert_organavailable_org_name_textfield.setVisible(false);
        insert_organavailable_donor_id_textfield.setVisible(false);
        insert_orgavailable_done_button.setVisible(false);
        
        
        
        insert_orghead_org_id_label.setVisible(false);
        insert_orghead_employee_id_label.setVisible(false);
        insert_orghead_name_label.setVisible(false);
        insert_orghead_date_of_joining_label.setVisible(false);
        insert_orghead_term_label.setVisible(false);
        insert_orghead_org_id_textfield.setVisible(false);
        insert_orghead_employee_id_textfield.setVisible(false);
        insert_orghead_name_textfield.setVisible(false);
        insert_orghead_date_of_joining_textfield.setVisible(false);
        insert_orghead_term_textfield.setVisible(false);
        insert_orghead_done_button.setVisible(false);
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
insert_organization_org_id_label.setVisible(false);
        insert_organization_name_label.setVisible(false);
        insert_organization_location_label.setVisible(false);
        insert_organization_govtapproved_label.setVisible(false);
        insert_organization_org_id_textfield.setVisible(false);
        insert_organization_name_textfield.setVisible(false);
        insert_organization_location_textfield.setVisible(false);
        insert_organization_govtapproved_textfield.setVisible(false);
        insert_organization_done_button.setVisible(false);
        
        
        insert_transaction_patient_id_label.setVisible(false);
        insert_transaction_organ_id_label.setVisible(false);
        insert_transaction_donor_id_label.setVisible(false);
        insert_transaction_date_of_transaction_label.setVisible(false);
        insert_transaction_status_label.setVisible(false);
        insert_transaction_patient_id_textfield.setVisible(false);
        insert_transaction_organ_id_textfield.setVisible(false);
        insert_transaction_donor_id_textfield.setVisible(false);
        insert_transaction_date_of_transaction_textfield.setVisible(false);
        insert_transaction_status_textfield.setVisible(false);
        insert_transaction_done_button.setVisible(false);
        
        
        insert_organavailable_org_id_label.setVisible(false);
        insert_organavailable_org_name_label.setVisible(false);
        insert_organavailable_donor_id_label.setVisible(false);
        insert_organavailable_org_id_textfield.setVisible(false);
        insert_organavailable_org_name_textfield.setVisible(false);
        insert_organavailable_donor_id_textfield.setVisible(false);
        insert_orgavailable_done_button.setVisible(false);
        
        
        
        insert_orghead_org_id_label.setVisible(true);
        insert_orghead_employee_id_label.setVisible(true);
        insert_orghead_name_label.setVisible(true);
        insert_orghead_date_of_joining_label.setVisible(true);
        insert_orghead_term_label.setVisible(true);
        insert_orghead_org_id_textfield.setVisible(true);
        insert_orghead_employee_id_textfield.setVisible(true);
        insert_orghead_name_textfield.setVisible(true);
        insert_orghead_date_of_joining_textfield.setVisible(true);
        insert_orghead_term_textfield.setVisible(true);
        insert_orghead_done_button.setVisible(true);
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void DISPLAY_ORGANIZATION_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DISPLAY_ORGANIZATION_BUTTONActionPerformed

        DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
        //                   tm.setRowCount(0);
        tm.setRowCount(0);

        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
            System.out.println("Exception caught --> " + e);
        }
        try{
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select ORGANIZATION_ID,ORGANIZATION_NAME,LOCATION,GOVERNMENT_APPROVED from organization");
            ResultSetMetaData meta=rs.getMetaData();
            int numberOfColumns=meta.getColumnCount();
            while(rs.next()){
                Object[] rowData=new Object[numberOfColumns];
                for (int i = 0; i < rowData.length; ++i) {
                    rowData[i]=rs.getObject(i+1);
                }
                tm.addRow(rowData);
            }

        }catch(Exception e){
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_DISPLAY_ORGANIZATION_BUTTONActionPerformed

    private void DISPLAY_TRANSACTIONS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DISPLAY_TRANSACTIONS_BUTTONActionPerformed

        DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
        //                   tm.setRowCount(0);
        tm.setRowCount(0);

        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
            System.out.println("Exception caught --> " + e);
        }
        try{
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select PATIENT_ID,ORGAN_ID,DONOR_ID,DATE_OF_TRANSACTION,STATUS from transaction");
            ResultSetMetaData meta=rs.getMetaData();
            int numberOfColumns=meta.getColumnCount();
            while(rs.next()){
                Object[] rowData=new Object[numberOfColumns];
                for (int i = 0; i < rowData.length; ++i) {
                    rowData[i]=rs.getObject(i+1);
                }
                tm.addRow(rowData);
            }

        }catch(Exception e){
            e.printStackTrace();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_DISPLAY_TRANSACTIONS_BUTTONActionPerformed

    private void DISPLAY_ORGHEAD_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DISPLAY_ORGHEAD_BUTTONActionPerformed

        DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
        //                   tm.setRowCount(0);
        tm.setRowCount(0);

        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
            System.out.println("Exception caught --> " + e);
        }
        try{
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select ORGANIZATION_ID,EMPLOYEE_ID,NAME,DATE_OF_JOINING,TERM_LENGTH from organization_head");
            ResultSetMetaData meta=rs.getMetaData();
            int numberOfColumns=meta.getColumnCount();
            while(rs.next()){
                Object[] rowData=new Object[numberOfColumns];
                for (int i = 0; i < rowData.length; ++i) {
                    rowData[i]=rs.getObject(i+1);
                }
                tm.addRow(rowData);
            }

        }catch(Exception e){
            e.printStackTrace();
        }           // TODO add your handling code here:
    }//GEN-LAST:event_DISPLAY_ORGHEAD_BUTTONActionPerformed

    private void DISPLAY_ORGAN_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DISPLAY_ORGAN_BUTTONActionPerformed

        DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
        //                   tm.setRowCount(0);
        tm.setRowCount(0);

        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
            System.out.println("Exception caught --> " + e);
        }
        try{
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select ORGAN_ID,ORGAN_NAME,DONOR_ID from organ_available");
            ResultSetMetaData meta=rs.getMetaData();
            int numberOfColumns=meta.getColumnCount();
            while(rs.next()){
                Object[] rowData=new Object[numberOfColumns];
                for (int i = 0; i < rowData.length; ++i) {
                    rowData[i]=rs.getObject(i+1);
                }
                tm.addRow(rowData);
            }

        }catch(Exception e){
            e.printStackTrace();
        }          // TODO add your handling code here:
    }//GEN-LAST:event_DISPLAY_ORGAN_BUTTONActionPerformed

    private void insert_organization_done_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_organization_done_buttonActionPerformed
 
        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e);
        }
        try{
            Statement st = conn.createStatement();
            int organization_id=Integer.parseInt(insert_organization_org_id_textfield.getText().toString());
            String organization_name=insert_organization_name_textfield.getText();
            String organization_location=insert_organization_location_textfield.getText();
            int organization_govtapproved=Integer.parseInt(insert_organization_govtapproved_textfield.getText());
            
            st.execute("insert into organization values('"+organization_id+"','"+organization_name+"','"+organization_location+"','"+organization_govtapproved+"')");
 JOptionPane.showMessageDialog(rootPane, "VALUES ENTERED SUCCESSFULLY!","DONE",JOptionPane.PLAIN_MESSAGE);
        
         insert_organization_org_id_textfield.setText(String.valueOf(Integer.parseInt(insert_organavailable_org_id_textfield.getText())+1));
         insert_organization_name_textfield.setText("");
         insert_organization_location_textfield.setText("");
         insert_organization_govtapproved_textfield.setText("");
            
        }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane, "Valued Entered in user_id or medical insurance should be number","ERROR",JOptionPane.ERROR_MESSAGE);
         insert_organization_org_id_textfield.setText("");
         insert_organization_name_textfield.setText("");
         insert_organization_location_textfield.setText("");
         insert_organization_govtapproved_textfield.setText("");
        }
        catch(SQLException e){
            System.out.println(e.getErrorCode());
            System.out.println(e.getMessage());
            if(e.getErrorCode()==20001){
                JOptionPane.showMessageDialog(rootPane, "Valued Entered in GOVT APPROVED field should be 1 or 0","ERROR",JOptionPane.ERROR_MESSAGE);
         
            }
//            else if(e.getErrorCode()==1){
//                JOptionPane.showMessageDialog(rootPane, "Valued Entered in PHONE NUMBER","ERROR",JOptionPane.ERROR_MESSAGE);
//         
//            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Please check all values entered","ERROR",JOptionPane.ERROR_MESSAGE);
         
            }
//        JOptionPane.showMessageDialog(rootPane, "Valued Entered in MEDICAL_INSURANCE field should be 1 or 0","ERROR",JOptionPane.ERROR_MESSAGE);
         insert_organization_org_id_textfield.setText("");
         insert_organization_name_textfield.setText("");
         insert_organization_location_textfield.setText("");
         insert_organization_govtapproved_textfield.setText("");
        }

        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_insert_organization_done_buttonActionPerformed

    private void insert_transaction_done_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_transaction_done_buttonActionPerformed
 
        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
            int transaction_patient_id=Integer.parseInt(insert_transaction_patient_id_textfield.getText().toString());
            int transaction_organ_id=Integer.parseInt(insert_transaction_organ_id_textfield.getText().toString());
            int transaction_donor_id=Integer.parseInt(insert_transaction_donor_id_textfield.getText().toString());
            String transaction_date=insert_transaction_date_of_transaction_textfield.getText();
            String transaction_status=insert_transaction_status_textfield.getText();
            
            st.execute("insert into transaction values('"+transaction_patient_id+"','"+transaction_organ_id+"','"+transaction_donor_id+"','"+transaction_date+"','"+transaction_status+"')");
 JOptionPane.showMessageDialog(rootPane, "VALUES ENTERED SUCCESSFULLY!","DONE",JOptionPane.PLAIN_MESSAGE);
        insert_transaction_patient_id_textfield.setText("");
         insert_transaction_organ_id_textfield.setText("");
         insert_transaction_donor_id_textfield.setText("");
         insert_transaction_date_of_transaction_textfield.setText("");
         insert_transaction_status_textfield.setText("");
        
            
        }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane, "Valued Entered in patient id ot organ id or donor id should be number","ERROR",JOptionPane.ERROR_MESSAGE);
         insert_transaction_patient_id_textfield.setText("");
         insert_transaction_organ_id_textfield.setText("");
         insert_transaction_donor_id_textfield.setText("");
         insert_transaction_date_of_transaction_textfield.setText("");
         insert_transaction_status_textfield.setText("");
        }
        catch(SQLException e){
            System.out.println(e.getErrorCode());
            System.out.println(e.getMessage());
            if(e.getErrorCode()==20001){
                JOptionPane.showMessageDialog(rootPane, "Valued Entered in STATUS field should be 1 or 0","ERROR",JOptionPane.ERROR_MESSAGE);
         
            }
//            else if(e.getErrorCode()==1){
//                JOptionPane.showMessageDialog(rootPane, "Valued Entered in PHONE NUMBER","ERROR",JOptionPane.ERROR_MESSAGE);
//         
//            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Please check all values entered","ERROR",JOptionPane.ERROR_MESSAGE);
         
            }
//        JOptionPane.showMessageDialog(rootPane, "Valued Entered in MEDICAL_INSURANCE field should be 1 or 0","ERROR",JOptionPane.ERROR_MESSAGE);
         insert_transaction_patient_id_textfield.setText("");
         insert_transaction_organ_id_textfield.setText("");
         insert_transaction_donor_id_textfield.setText("");
         insert_transaction_date_of_transaction_textfield.setText("");
         insert_transaction_status_textfield.setText("");
        }

        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_insert_transaction_done_buttonActionPerformed

    private void insert_orgavailable_done_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_orgavailable_done_buttonActionPerformed
 
        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
            int organization_id=Integer.parseInt(insert_organavailable_org_id_textfield.getText().toString());
            String organization_name=insert_organavailable_org_name_textfield.getText();
            int donor_id=Integer.parseInt(insert_organavailable_donor_id_textfield.getText().toString());
            
            st.execute("insert into organ_available values('"+organization_id+"','"+organization_name+"','"+donor_id+"')");

             JOptionPane.showMessageDialog(rootPane, "VALUES ENTERED SUCCESSFULLY!","DONE",JOptionPane.PLAIN_MESSAGE);
         insert_organavailable_org_id_textfield.setText("");
         insert_organavailable_org_name_textfield.setText("");
         insert_organavailable_donor_id_textfield.setText("");
        
        }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane, "Valued Entered in organization id or donor id should be number","ERROR",JOptionPane.ERROR_MESSAGE);
         insert_organavailable_org_id_textfield.setText("");
         insert_organavailable_org_name_textfield.setText("");
         insert_organavailable_donor_id_textfield.setText("");
         }
        catch(SQLException e){
            System.out.println(e.getErrorCode());
            System.out.println(e.getMessage());
//            if(e.getErrorCode()==20001){
//                JOptionPane.showMessageDialog(rootPane, "Valued Entered in STATUS field should be 1 or 0","ERROR",JOptionPane.ERROR_MESSAGE);
//         
//            }
//            else if(e.getErrorCode()==1){
//                JOptionPane.showMessageDialog(rootPane, "Valued Entered in PHONE NUMBER","ERROR",JOptionPane.ERROR_MESSAGE);
//         
//            }
//            else{
                JOptionPane.showMessageDialog(rootPane, "Please check all values entered","ERROR",JOptionPane.ERROR_MESSAGE);
         
//            }
//        JOptionPane.showMessageDialog(rootPane, "Valued Entered in MEDICAL_INSURANCE field should be 1 or 0","ERROR",JOptionPane.ERROR_MESSAGE);
         insert_organavailable_org_id_textfield.setText("");
         insert_organavailable_org_name_textfield.setText("");
         insert_organavailable_donor_id_textfield.setText("");
         }
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_insert_orgavailable_done_buttonActionPerformed

    private void insert_orghead_done_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_orghead_done_buttonActionPerformed
 
 Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
            int organization_id=Integer.parseInt(insert_orghead_org_id_textfield.getText().toString());
            int employee_id=Integer.parseInt(insert_orghead_employee_id_textfield.getText().toString());
            String name=insert_orghead_name_textfield.getText();
            String date=insert_orghead_date_of_joining_textfield.getText().toString();
            int term=Integer.parseInt(insert_orghead_term_textfield.getText().toString());
            
            st.execute("insert into organization_head values('"+organization_id+"','"+employee_id+"','"+name+"','"+date+"','"+term+"')");

             JOptionPane.showMessageDialog(rootPane, "VALUES ENTERED SUCCESSFULLY!","DONE",JOptionPane.PLAIN_MESSAGE);
        insert_orghead_org_id_textfield.setText("");
         insert_orghead_employee_id_textfield.setText("");
         insert_orghead_name_textfield.setText("");
         insert_orghead_date_of_joining_textfield.setText("");
         insert_orghead_term_textfield.setText("");
        
        }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane, "Valued Entered in organization id or employee id or term length should be number","ERROR",JOptionPane.ERROR_MESSAGE);
         insert_orghead_org_id_textfield.setText("");
         insert_orghead_employee_id_textfield.setText("");
         insert_orghead_name_textfield.setText("");
         insert_orghead_date_of_joining_textfield.setText("");
         insert_orghead_term_textfield.setText("");
        }
        catch(SQLException e){
            System.out.println(e.getErrorCode());
            System.out.println(e.getMessage());
//            if(e.getErrorCode()==20001){
//                JOptionPane.showMessageDialog(rootPane, "Valued Entered in STATUS field should be 1 or 0","ERROR",JOptionPane.ERROR_MESSAGE);
//         
//            }
//            else if(e.getErrorCode()==1){
//                JOptionPane.showMessageDialog(rootPane, "Valued Entered in PHONE NUMBER","ERROR",JOptionPane.ERROR_MESSAGE);
//         
//            }
//            else{
                JOptionPane.showMessageDialog(rootPane, "Please check all values entered","ERROR",JOptionPane.ERROR_MESSAGE);
         
//            }
//        JOptionPane.showMessageDialog(rootPane, "Valued Entered in MEDICAL_INSURANCE field should be 1 or 0","ERROR",JOptionPane.ERROR_MESSAGE);
         insert_orghead_org_id_textfield.setText("");
         insert_orghead_employee_id_textfield.setText("");
         insert_orghead_name_textfield.setText("");
         insert_orghead_date_of_joining_textfield.setText("");
         insert_orghead_term_textfield.setText("");
         }
        

        
               // TODO add your handling code here:
    }//GEN-LAST:event_insert_orghead_done_buttonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// JOptionPane.showMessageDialog(null, "LOGIN SUCCESSFULL");
        try {
            //                jTextField4.setText("Welcome");
            //  System.out.println(user);
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Insert_Screen_2.class.getName()).log(Level.SEVERE, null, ex);
        }
                 this.dispose();
                 
              // new projectjava.LoginPage.c1();
               new dbms.SIUD().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert_Screen_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert_Screen_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert_Screen_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert_Screen_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert_Screen_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DISPLAY_ORGANIZATION_BUTTON;
    private javax.swing.JButton DISPLAY_ORGAN_BUTTON;
    private javax.swing.JButton DISPLAY_ORGHEAD_BUTTON;
    private javax.swing.JButton DISPLAY_TRANSACTIONS_BUTTON;
    private javax.swing.JLabel insert_organavailable_donor_id_label;
    private javax.swing.JTextField insert_organavailable_donor_id_textfield;
    private javax.swing.JLabel insert_organavailable_org_id_label;
    private javax.swing.JTextField insert_organavailable_org_id_textfield;
    private javax.swing.JLabel insert_organavailable_org_name_label;
    private javax.swing.JTextField insert_organavailable_org_name_textfield;
    private javax.swing.JButton insert_organization_done_button;
    private javax.swing.JLabel insert_organization_govtapproved_label;
    private javax.swing.JTextField insert_organization_govtapproved_textfield;
    private javax.swing.JLabel insert_organization_location_label;
    private javax.swing.JTextField insert_organization_location_textfield;
    private javax.swing.JLabel insert_organization_name_label;
    private javax.swing.JTextField insert_organization_name_textfield;
    private javax.swing.JLabel insert_organization_org_id_label;
    private javax.swing.JLabel insert_organization_org_id_textfield;
    private javax.swing.JButton insert_orgavailable_done_button;
    private javax.swing.JLabel insert_orghead_date_of_joining_label;
    private javax.swing.JTextField insert_orghead_date_of_joining_textfield;
    private javax.swing.JButton insert_orghead_done_button;
    private javax.swing.JLabel insert_orghead_employee_id_label;
    private javax.swing.JTextField insert_orghead_employee_id_textfield;
    private javax.swing.JLabel insert_orghead_name_label;
    private javax.swing.JTextField insert_orghead_name_textfield;
    private javax.swing.JLabel insert_orghead_org_id_label;
    private javax.swing.JTextField insert_orghead_org_id_textfield;
    private javax.swing.JLabel insert_orghead_term_label;
    private javax.swing.JTextField insert_orghead_term_textfield;
    private javax.swing.JLabel insert_transaction_date_of_transaction_label;
    private javax.swing.JTextField insert_transaction_date_of_transaction_textfield;
    private javax.swing.JButton insert_transaction_done_button;
    private javax.swing.JLabel insert_transaction_donor_id_label;
    private javax.swing.JTextField insert_transaction_donor_id_textfield;
    private javax.swing.JLabel insert_transaction_organ_id_label;
    private javax.swing.JTextField insert_transaction_organ_id_textfield;
    private javax.swing.JLabel insert_transaction_patient_id_label;
    private javax.swing.JTextField insert_transaction_patient_id_textfield;
    private javax.swing.JLabel insert_transaction_status_label;
    private javax.swing.JTextField insert_transaction_status_textfield;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
