/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Meet
 */
public class Search_Screen extends javax.swing.JFrame {

    /**
     * Creates new form Search_Screen
     */
    public Search_Screen() {
        initComponents();
        serach_by_user_ComboBox.setVisible(false);
        serach_by_patient_ComboBox.setVisible(false);
        serach_by_donor_ComboBox.setVisible(false);
        serach_by_doctor_ComboBox.setVisible(false);
        
        serach_by_user_Donebutton.setVisible(false);
        serach_by_patient_Donebutton.setVisible(false);
        serach_by_donor_Donebutton.setVisible(false);
        serach_by_doctor_Donebutton.setVisible(false);
        
        serach_by_user_label.setVisible(false);
        serach_by_patient_label.setVisible(false);
        serach_by_donor_label.setVisible(false);
        serach_by_doctor_label.setVisible(false);
        
        serach_by_user_textfield.setVisible(false);
        serach_by_patient_textfield.setVisible(false);
        serach_by_donor_textfield.setVisible(false);
        serach_by_doctor_textfield.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        search_by_user_button = new javax.swing.JButton();
        search_by_patient_button = new javax.swing.JButton();
        search_by_donor_button = new javax.swing.JButton();
        search_by_doctor_button = new javax.swing.JButton();
        serach_by_user_label = new javax.swing.JLabel();
        serach_by_user_textfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        serach_by_patient_Donebutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        serach_by_user_Donebutton = new javax.swing.JButton();
        serach_by_doctor_Donebutton = new javax.swing.JButton();
        serach_by_donor_Donebutton = new javax.swing.JButton();
        serach_by_user_ComboBox = new javax.swing.JComboBox<>();
        serach_by_patient_ComboBox = new javax.swing.JComboBox<>();
        serach_by_donor_ComboBox = new javax.swing.JComboBox<>();
        serach_by_doctor_ComboBox = new javax.swing.JComboBox<>();
        serach_by_patient_label = new javax.swing.JLabel();
        serach_by_patient_textfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        serach_by_donor_label = new javax.swing.JLabel();
        serach_by_donor_textfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        serach_by_doctor_label = new javax.swing.JLabel();
        serach_by_doctor_textfield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        search_by_user_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        search_by_user_button.setText("Search By User ");
        search_by_user_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_user_buttonActionPerformed(evt);
            }
        });

        search_by_patient_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        search_by_patient_button.setText("Search By Patient");
        search_by_patient_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_patient_buttonActionPerformed(evt);
            }
        });

        search_by_donor_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        search_by_donor_button.setText("Search By Donor");
        search_by_donor_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_donor_buttonActionPerformed(evt);
            }
        });

        search_by_doctor_button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        search_by_doctor_button.setText("Search By Doctor");
        search_by_doctor_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_doctor_buttonActionPerformed(evt);
            }
        });

        serach_by_user_label.setBackground(new java.awt.Color(0, 102, 102));
        serach_by_user_label.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        serach_by_user_label.setForeground(new java.awt.Color(255, 255, 255));
        serach_by_user_label.setText("Name");

        serach_by_user_textfield.setBackground(new java.awt.Color(0, 102, 102));
        serach_by_user_textfield.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        serach_by_user_textfield.setForeground(new java.awt.Color(255, 255, 255));
        serach_by_user_textfield.setBorder(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setText("Back");

        serach_by_patient_Donebutton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        serach_by_patient_Donebutton.setText("Done");
        serach_by_patient_Donebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serach_by_patient_DonebuttonActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        serach_by_user_Donebutton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        serach_by_user_Donebutton.setText("Done");
        serach_by_user_Donebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serach_by_user_DonebuttonActionPerformed(evt);
            }
        });

        serach_by_doctor_Donebutton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        serach_by_doctor_Donebutton.setText("Done");
        serach_by_doctor_Donebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serach_by_doctor_DonebuttonActionPerformed(evt);
            }
        });

        serach_by_donor_Donebutton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        serach_by_donor_Donebutton.setText("Done");
        serach_by_donor_Donebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serach_by_donor_DonebuttonActionPerformed(evt);
            }
        });

        serach_by_user_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USER_ID", "NAME", "DATE_OF_BIRTH", "MEDICAL_INSURANCE", "MEDICAL_HISTORY", "STREET", "CITY", "STATE" }));

        serach_by_patient_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PATIENT_ID", "ORGAN_REQ", "REASON_OF_PROCUREMENT", "DOCTOR_ID", "USER_ID" }));

        serach_by_donor_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DONOR_ID", "ORGAN_DONATED", "REASON_OF_DONATION", "ORGANIZATION_ID", "USER_ID" }));

        serach_by_doctor_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DOCTOR_ID", "DOCTOR_NAME", "DEPARTMENT_NAME", "ORGANIZATION_ID" }));

        serach_by_patient_label.setBackground(new java.awt.Color(0, 102, 102));
        serach_by_patient_label.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        serach_by_patient_label.setForeground(new java.awt.Color(255, 255, 255));
        serach_by_patient_label.setText("Name");

        serach_by_patient_textfield.setBackground(new java.awt.Color(0, 102, 102));
        serach_by_patient_textfield.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        serach_by_patient_textfield.setForeground(new java.awt.Color(255, 255, 255));
        serach_by_patient_textfield.setBorder(null);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        serach_by_donor_label.setBackground(new java.awt.Color(0, 102, 102));
        serach_by_donor_label.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        serach_by_donor_label.setForeground(new java.awt.Color(255, 255, 255));
        serach_by_donor_label.setText("Name");

        serach_by_donor_textfield.setBackground(new java.awt.Color(0, 102, 102));
        serach_by_donor_textfield.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        serach_by_donor_textfield.setForeground(new java.awt.Color(255, 255, 255));
        serach_by_donor_textfield.setBorder(null);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        serach_by_doctor_label.setBackground(new java.awt.Color(0, 102, 102));
        serach_by_doctor_label.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        serach_by_doctor_label.setForeground(new java.awt.Color(255, 255, 255));
        serach_by_doctor_label.setText("Name");

        serach_by_doctor_textfield.setBackground(new java.awt.Color(0, 102, 102));
        serach_by_doctor_textfield.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        serach_by_doctor_textfield.setForeground(new java.awt.Color(255, 255, 255));
        serach_by_doctor_textfield.setBorder(null);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(search_by_user_button, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(search_by_patient_button)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(search_by_donor_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(search_by_doctor_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(99, 99, 99)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(serach_by_donor_Donebutton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(serach_by_donor_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(serach_by_user_Donebutton)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(serach_by_doctor_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(serach_by_doctor_label))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(serach_by_user_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(serach_by_user_label))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(serach_by_patient_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(serach_by_donor_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(serach_by_donor_label)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                            .addGap(252, 252, 252)
                                                            .addComponent(serach_by_patient_label)))))
                                            .addComponent(serach_by_patient_Donebutton)
                                            .addComponent(serach_by_doctor_Donebutton))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(serach_by_patient_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(serach_by_user_textfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(serach_by_doctor_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search_by_user_button)
                            .addComponent(serach_by_user_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serach_by_user_label)
                            .addComponent(serach_by_user_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(serach_by_user_Donebutton)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(serach_by_patient_label)
                                        .addComponent(serach_by_patient_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(search_by_patient_button)
                                    .addComponent(serach_by_patient_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(91, 91, 91)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(search_by_donor_button)
                                            .addComponent(serach_by_donor_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(serach_by_patient_Donebutton))
                                .addGap(18, 18, 18)
                                .addComponent(serach_by_donor_Donebutton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(serach_by_donor_label)
                                    .addComponent(serach_by_donor_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)))
                        .addGap(42, 42, 42)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(search_by_doctor_button)
                        .addComponent(serach_by_doctor_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(serach_by_doctor_label))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(serach_by_doctor_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serach_by_doctor_Donebutton)
                .addGap(251, 251, 251))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_by_donor_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_donor_buttonActionPerformed
        serach_by_user_ComboBox.setVisible(false);
        serach_by_patient_ComboBox.setVisible(false);
        serach_by_doctor_ComboBox.setVisible(false);
        
        serach_by_user_Donebutton.setVisible(false);
        serach_by_patient_Donebutton.setVisible(false);
        serach_by_doctor_Donebutton.setVisible(false);
        
        serach_by_user_label.setVisible(false);
        serach_by_patient_label.setVisible(false);
        serach_by_doctor_label.setVisible(false);
        
        serach_by_user_textfield.setVisible(false);
        serach_by_patient_textfield.setVisible(false);
        serach_by_doctor_textfield.setVisible(false);


        serach_by_donor_ComboBox.setVisible(true);
        serach_by_donor_Donebutton.setVisible(true);
        serach_by_donor_label.setVisible(true);
        serach_by_donor_textfield.setVisible(true);
       
        
// TODO add your handling code here:
    }//GEN-LAST:event_search_by_donor_buttonActionPerformed

    private void serach_by_user_DonebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serach_by_user_DonebuttonActionPerformed
DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
//                   tm.setRowCount(0);
                                  tm.setRowCount(0);
 
        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
//            System.out.println(jComboBox1.getSelectedItem());
//            System.out.println(jTextField1.getText());
                String colname=serach_by_user_ComboBox.getSelectedItem().toString();
                String value=serach_by_user_textfield.getText();
ResultSet rs = st.executeQuery("select * from user1 where "+colname+"='"+value+"'");
ResultSetMetaData meta=rs.getMetaData();
int numberOfColumns=meta.getColumnCount();
            while(rs.next()){
//                int no = rs.getInt(1);
//                String name = rs.getString(2);
//                System.out.println("no: "+no+" name: "+name);
                    Object[] rowData=new Object[numberOfColumns];
                    for (int i = 0; i < rowData.length; ++i) {
                    rowData[i]=rs.getObject(i+1);
                }
                  tm.addRow(rowData);
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_serach_by_user_DonebuttonActionPerformed

    private void search_by_user_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_user_buttonActionPerformed
        serach_by_patient_ComboBox.setVisible(false);
        serach_by_donor_ComboBox.setVisible(false);
        serach_by_doctor_ComboBox.setVisible(false);
        
        serach_by_patient_Donebutton.setVisible(false);
        serach_by_donor_Donebutton.setVisible(false);
        serach_by_doctor_Donebutton.setVisible(false);
        
        serach_by_patient_label.setVisible(false);
        serach_by_donor_label.setVisible(false);
        serach_by_doctor_label.setVisible(false);
        
        serach_by_patient_textfield.setVisible(false);
        serach_by_donor_textfield.setVisible(false);
        serach_by_doctor_textfield.setVisible(false);
               
        serach_by_user_ComboBox.setVisible(true);
        serach_by_user_Donebutton.setVisible(true);
        serach_by_user_label.setVisible(true);
        serach_by_user_textfield.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_search_by_user_buttonActionPerformed

    private void search_by_patient_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_patient_buttonActionPerformed

        serach_by_user_ComboBox.setVisible(false);
        serach_by_donor_ComboBox.setVisible(false);
        serach_by_doctor_ComboBox.setVisible(false);
        
        serach_by_user_Donebutton.setVisible(false);
        serach_by_donor_Donebutton.setVisible(false);
        serach_by_doctor_Donebutton.setVisible(false);
        
        serach_by_user_label.setVisible(false);
        serach_by_donor_label.setVisible(false);
        serach_by_doctor_label.setVisible(false);
        
        serach_by_user_textfield.setVisible(false);
        serach_by_donor_textfield.setVisible(false);
        serach_by_doctor_textfield.setVisible(false);        // TODO add your handling code here:
        
        
        serach_by_patient_ComboBox.setVisible(true);
        serach_by_patient_Donebutton.setVisible(true);
        serach_by_patient_label.setVisible(true);
        serach_by_patient_textfield.setVisible(true);
        
        
        
        
        
        
    }//GEN-LAST:event_search_by_patient_buttonActionPerformed

    private void search_by_doctor_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_doctor_buttonActionPerformed

        serach_by_user_ComboBox.setVisible(false);
        serach_by_patient_ComboBox.setVisible(false);
        serach_by_donor_ComboBox.setVisible(false);
        
        serach_by_user_Donebutton.setVisible(false);
        serach_by_patient_Donebutton.setVisible(false);
        serach_by_donor_Donebutton.setVisible(false);
        
        serach_by_user_label.setVisible(false);
        serach_by_patient_label.setVisible(false);
        serach_by_donor_label.setVisible(false);
        
        serach_by_user_textfield.setVisible(false);
        serach_by_patient_textfield.setVisible(false);
        serach_by_donor_textfield.setVisible(false);
         

        serach_by_doctor_ComboBox.setVisible(true);
        serach_by_doctor_Donebutton.setVisible(true);
        serach_by_doctor_label.setVisible(true);
        serach_by_doctor_textfield.setVisible(true);
                



// TODO add your handling code here:
    }//GEN-LAST:event_search_by_doctor_buttonActionPerformed

    private void serach_by_patient_DonebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serach_by_patient_DonebuttonActionPerformed
DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
//                   tm.setRowCount(0);
                tm.setRowCount(0);
        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
//            System.out.println(jComboBox1.getSelectedItem());
//            System.out.println(jTextField1.getText());
                String colname=serach_by_patient_ComboBox.getSelectedItem().toString();
                String value=serach_by_patient_textfield.getText();
ResultSet rs = st.executeQuery("select * from patient where "+colname+"='"+value+"'");
ResultSetMetaData meta=rs.getMetaData();
int numberOfColumns=meta.getColumnCount();
            while(rs.next()){
//                int no = rs.getInt(1);
//                String name = rs.getString(2);
//                System.out.println("no: "+no+" name: "+name);
                    Object[] rowData=new Object[numberOfColumns];
                    for (int i = 0; i < rowData.length; ++i) {
                    rowData[i]=rs.getObject(i+1);
                }
                  tm.addRow(rowData);
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_serach_by_patient_DonebuttonActionPerformed

    private void serach_by_donor_DonebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serach_by_donor_DonebuttonActionPerformed
DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
//                   tm.setRowCount(0);
                                   tm.setRowCount(0);

        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
//            System.out.println(jComboBox1.getSelectedItem());
//            System.out.println(jTextField1.getText());
                String colname=serach_by_donor_ComboBox.getSelectedItem().toString();
                String value=serach_by_donor_textfield.getText();
ResultSet rs = st.executeQuery("select * from donor where "+colname+"='"+value+"'");
ResultSetMetaData meta=rs.getMetaData();
int numberOfColumns=meta.getColumnCount();
            while(rs.next()){
//                int no = rs.getInt(1);
//                String name = rs.getString(2);
//                System.out.println("no: "+no+" name: "+name);
                    Object[] rowData=new Object[numberOfColumns];
                    for (int i = 0; i < rowData.length; ++i) {
                    rowData[i]=rs.getObject(i+1);
                }
                  tm.addRow(rowData);
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_serach_by_donor_DonebuttonActionPerformed

    private void serach_by_doctor_DonebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serach_by_doctor_DonebuttonActionPerformed
DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
//                   tm.setRowCount(0);
                                   tm.setRowCount(0);

        Connection conn = null;
        try{
            String driverName = "oracle.jdbc.OracleDriver";
            Class.forName(driverName);
            String serverName = "LAPTOP-CAL2CB75";
            String serverPort = "1522";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName +":" + serverPort + ":" + sid;
            String username = "VARSHIL";
            String password = "admin";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Successful login");
        }catch(Exception e){
           System.out.println("Exception caught --> " + e); 
        }
        try{
            Statement st = conn.createStatement();
//            System.out.println(jComboBox1.getSelectedItem());
//            System.out.println(jTextField1.getText());
                String colname=serach_by_doctor_ComboBox.getSelectedItem().toString();
                String value=serach_by_doctor_textfield.getText();
ResultSet rs = st.executeQuery("select * from doctor where "+colname+"='"+value+"'");
ResultSetMetaData meta=rs.getMetaData();
int numberOfColumns=meta.getColumnCount();
            while(rs.next()){
//                int no = rs.getInt(1);
//                String name = rs.getString(2);
//                System.out.println("no: "+no+" name: "+name);
                    Object[] rowData=new Object[numberOfColumns];
                    for (int i = 0; i < rowData.length; ++i) {
                    rowData[i]=rs.getObject(i+1);
                }
                  tm.addRow(rowData);
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_serach_by_doctor_DonebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_Screen().setVisible(true);
                }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton search_by_doctor_button;
    private javax.swing.JButton search_by_donor_button;
    private javax.swing.JButton search_by_patient_button;
    private javax.swing.JButton search_by_user_button;
    private javax.swing.JComboBox<String> serach_by_doctor_ComboBox;
    private javax.swing.JButton serach_by_doctor_Donebutton;
    private javax.swing.JLabel serach_by_doctor_label;
    private javax.swing.JTextField serach_by_doctor_textfield;
    private javax.swing.JComboBox<String> serach_by_donor_ComboBox;
    private javax.swing.JButton serach_by_donor_Donebutton;
    private javax.swing.JLabel serach_by_donor_label;
    private javax.swing.JTextField serach_by_donor_textfield;
    private javax.swing.JComboBox<String> serach_by_patient_ComboBox;
    private javax.swing.JButton serach_by_patient_Donebutton;
    private javax.swing.JLabel serach_by_patient_label;
    private javax.swing.JTextField serach_by_patient_textfield;
    private javax.swing.JComboBox<String> serach_by_user_ComboBox;
    private javax.swing.JButton serach_by_user_Donebutton;
    private javax.swing.JLabel serach_by_user_label;
    private javax.swing.JTextField serach_by_user_textfield;
    // End of variables declaration//GEN-END:variables
}
